### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by CharlieEriksen** [OWASP/Amass#17]
Not sure what triggers this. Running on `2.5.0`. May be related to running multiple amass processes at once. 

It'd be awesome if this could be handled gracefully!
```
panic: send on closed channel

goroutine 317741 [running]:
github.com/OWASP/Amass/amass.(*Enumeration).Start.func1(0xc423336780)
        /go/src/github.com/OWASP/Amass/parts/amass/go/src/github.com/OWASP/Amass/amass/amass.go:205 +0x114
reflect.Value.call(0x8a3f60, 0xc42000c260, 0x13, 0x958236, 0x4, 0xc42275c300, 0x1, 0x1, 0xc423336780, 0xc423c59de0, ...)
        /go/src/github.com/OWASP/Amass/parts/go/build/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x8a3f60, 0xc42000c260, 0x13, 0xc42275c300, 0x1, 0x1, 0xc42275c300, 0x1, 0x1)
        /go/src/github.com/OWASP/Amass/parts/go/build/src/reflect/value.go:308 +0xa4
github.com/asaskevich/EventBus.(*EventBus).doPublish(0xc42000c240, 0xc42009bc50, 0x95e934, 0xc, 0xc423c59de0, 0x1, 0x1)
        /go/src/github.com/OWASP/Amass/parts/amass/go/src/github.com/asaskevich/EventBus/event_bus.go:158 +0xa8
github.com/asaskevich/EventBus.(*EventBus).doPublishAsync(0xc42000c240, 0xc42009bc50, 0x95e934, 0xc, 0xc423c59de0, 0x1, 0x1)
        /go/src/github.com/OWASP/Amass/parts/amass/go/src/github.com/asaskevich/EventBus/event_bus.go:166 +0xa3
created by github.com/asaskevich/EventBus.(*EventBus).Publish
        /go/src/github.com/OWASP/Amass/parts/amass/go/src/github.com/asaskevich/EventBus/event_bus.go:150 +0x28b
```

**Comment by subfission** [comment]
Same issue, but only 1 instance running.  Fails with both 1 target and a list of targets.  This just appeared for me too since the previous version worked fine.

**Comment by CharlieEriksen** [comment]
I'm 99% sure this is new in 2.5.0. I've had it occur now also with just 1 process. 

Whatever the change, I imagine it should be able to gracefully recover from a closed channel.

**Comment by caffix** [comment]
Can you please try it again with version 2.5.1? Thank you.

**Comment by CharlieEriksen** [comment]
Yet to run into it again on 2.5.1. Seems much more stable.

**Comment by caffix** [comment]
I'll be closing this issue then. Thanks.
