### ISSUE TITLE
Run time SIGSEGV running multiple domains 

### ISSUE THREAD

**Issue by roeyaus** [OWASP/Amass#170]
Calling Amass from my Golang program, while running a batch of ~1000 domains , with Passive=true and MaxDNSQueries = 20,  I encountered this : 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12e0aff]

goroutine 224 [running]:
regexp.(*Regexp).doExecute(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc015426e80, 0x19, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.12.1/libexec/src/regexp/exec.go:527 +0x6f
regexp.(*Regexp).doMatch(...)
	/usr/local/Cellar/go/1.12.1/libexec/src/regexp/exec.go:514
regexp.(*Regexp).MatchString(...)
	/usr/local/Cellar/go/1.12.1/libexec/src/regexp/regexp.go:468
github.com/OWASP/Amass/amass/sources.(*ThreatCrowd).executeQuery(0xc0000ef710, 0xc004cb1160, 0xa)
	/Users/roey.lehman/upguard/go/pkg/mod/github.com/!o!w!a!s!p/!amass@v0.0.0-20190518015002-9905bc9deaf8/amass/sources/threatcrowd.go:82 +0x4cd
github.com/OWASP/Amass/amass/sources.(*ThreatCrowd).processRequests(0xc0000ef710)
	/Users/roey.lehman/upguard/go/pkg/mod/github.com/!o!w!a!s!p/!amass@v0.0.0-20190518015002-9905bc9deaf8/amass/sources/threatcrowd.go:45 +0x12a
created by github.com/OWASP/Amass/amass/sources.(*ThreatCrowd).OnStart
	/Users/roey.lehman/upguard/go/pkg/mod/github.com/!o!w!a!s!p/!amass@v0.0.0-20190518015002-9905bc9deaf8/amass/sources/threatcrowd.go:34 +0x42
exit status 2
```

**Comment by roeyaus** [comment]
Another similar problem I assume, this time with Riddler : 

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x12e57e7]

goroutine 233 [running]:
regexp.(*Regexp).allMatches(0x0, 0xc01c382000, 0x6476, 0x0, 0x0, 0x0, 0x6477, 0xc0097c1dd0)
	/usr/local/Cellar/go/1.12.1/libexec/src/regexp/regexp.go:719 +0x127
regexp.(*Regexp).FindAllString(0x0, 0xc01c382000, 0x6476, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12.1/libexec/src/regexp/regexp.go:1060 +0xba
github.com/OWASP/Amass/amass/sources.(*Riddler).executeQuery(0xc00013b4d0, 0xc004cb5160, 0xa)
	/Users/roey.lehman/upguard/go/pkg/mod/github.com/!o!w!a!s!p/!amass@v0.0.0-20190518015002-9905bc9deaf8/amass/sources/riddler.go:59 +0x18b
github.com/OWASP/Amass/amass/sources.(*Riddler).processRequests(0xc00013b4d0)
	/Users/roey.lehman/upguard/go/pkg/mod/github.com/!o!w!a!s!p/!amass@v0.0.0-20190518015002-9905bc9deaf8/amass/sources/riddler.go:43 +0x12a
created by github.com/OWASP/Amass/amass/sources.(*Riddler).OnStart
	/Users/roey.lehman/upguard/go/pkg/mod/github.com/!o!w!a!s!p/!amass@v0.0.0-20190518015002-9905bc9deaf8/amass/sources/riddler.go:32 +0x42
```
