### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by riramar** [OWASP/Amass#20]
I'm getting the error below for a specific host that I cannot disclose.

```
# amass -active -brute -r 8.8.8.8,1.1.1.1 -whois -d redacted.com -o amass.txt
...
after a few domains
...
panic: runtime error: index out of range

goroutine 31 [running]:
github.com/OWASP/Amass/amass.parseASNInfo(0xc42f7f9860, 0x21, 0x94417c)
	/root/go/src/github.com/OWASP/Amass/amass/network.go:333 +0x337
github.com/OWASP/Amass/amass.asnLookup(0xe6a5, 0xc42017ac60, 0xe6a5, 0xc3fe20)
	/root/go/src/github.com/OWASP/Amass/amass/network.go:279 +0x20b
github.com/OWASP/Amass/amass.fetchOnlineData(0xc43702cec2, 0xe, 0xe6a5, 0x0, 0x0, 0x0)
	/root/go/src/github.com/OWASP/Amass/amass/network.go:222 +0x24f
github.com/OWASP/Amass/amass.IPRequest(0xc43702cec2, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/OWASP/Amass/amass/network.go:91 +0xde
github.com/OWASP/Amass/amass.(*DataManagerService).insertDomain(0xc42074aaa0, 0xc436d47768, 0x8)
	/root/go/src/github.com/OWASP/Amass/amass/datamgmtsrv.go:169 +0x2ec
github.com/OWASP/Amass/amass.(*DataManagerService).insertMX(0xc42074aaa0, 0xc435a4a840, 0x2)
	/root/go/src/github.com/OWASP/Amass/amass/datamgmtsrv.go:321 +0x120
github.com/OWASP/Amass/amass.(*DataManagerService).manageData(0xc42074aaa0)
	/root/go/src/github.com/OWASP/Amass/amass/datamgmtsrv.go:133 +0x319
github.com/OWASP/Amass/amass.(*DataManagerService).processRequests(0xc42074aaa0)
	/root/go/src/github.com/OWASP/Amass/amass/datamgmtsrv.go:80 +0x8f
created by github.com/OWASP/Amass/amass.(*DataManagerService).OnStart
	/root/go/src/github.com/OWASP/Amass/amass/datamgmtsrv.go:57 +0x1b6
# amass --version
version v2.5.2
```

**Comment by caffix** [comment]
Thank you for letting us know about the bug! It should be fixed in version 2.6.1
