### ISSUE TITLE
Error: goroutine 45944701 [IO wait]

### ISSUE THREAD

**Issue by CharlieEriksen** [OWASP/Amass#25]
```
goroutine 45944701 [IO wait]:
internal/poll.runtime_pollWait(0x7f079c2d69b0, 0x72, 0xc5c48d58b8)
        /go/src/github.com/OWASP/Amass/parts/go/build/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc5b2964d18, 0x72, 0xffffffffffffff00, 0x9a7d20, 0xbe0580)
        /go/src/github.com/OWASP/Amass/parts/go/build/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc5b2964d18, 0xc5353dda00, 0x200, 0x200)
        /go/src/github.com/OWASP/Amass/parts/go/build/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc5b2964d00, 0xc5353dda00, 0x200, 0x200, 0x0, 0x0, 0x0)
        /go/src/github.com/OWASP/Amass/parts/go/build/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc5b2964d00, 0xc5353dda00, 0x200, 0x200, 0x0, 0x200, 0xc5353dda00)
        /go/src/github.com/OWASP/Amass/parts/go/build/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc5c2fdf358, 0xc5353dda00, 0x200, 0x200, 0x0, 0x0, 0x0)
        /go/src/github.com/OWASP/Amass/parts/go/build/src/net/net.go:176 +0x6a
github.com/miekg/dns.(*Conn).Read(0xc5c48d5c98, 0xc5353dda00, 0x200, 0x200, 0x200, 0x200, 0xc5c48d5a80)
        /go/src/github.com/OWASP/Amass/parts/amass/go/src/github.com/miekg/dns/client.go:414 +0x1c7
github.com/miekg/dns.(*Conn).ReadMsgHeader(0xc5c48d5c98, 0x0, 0x97bfedfe09c, 0xc266e0, 0x72, 0x0, 0x0)
        /go/src/github.com/OWASP/Amass/parts/amass/go/src/github.com/miekg/dns/client.go:327 +0x3a4
github.com/miekg/dns.(*Conn).ReadMsg(0xc5c48d5c98, 0xbedadf4916010d0a, 0x97bfedfe09c, 0xc266e0)
        /go/src/github.com/OWASP/Amass/parts/amass/go/src/github.com/miekg/dns/client.go:278 +0x49
github.com/OWASP/Amass/amass/dnssrv.ExchangeConn(0x9adce0, 0xc5c2fdf358, 0xc467fff320, 0x2f, 0x5, 0x0, 0x9adce0, 0xc5c2fdf358, 0x0, 0x0)
        /go/src/github.com/OWASP/Amass/parts/amass/go/src/github.com/OWASP/Amass/amass/dnssrv/support.go:109 +0x18b
github.com/OWASP/Amass/amass/dnssrv.Resolve(0xc467fff320, 0x2f, 0x944076, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/OWASP/Amass/parts/amass/go/src/github.com/OWASP/Amass/amass/dnssrv/support.go:30 +0x1db
github.com/OWASP/Amass/amass/dnssrv.wildcardTestResolution(0xc42afd5900, 0xf, 0x3, 0x942e85, 0x1)
        /go/src/github.com/OWASP/Amass/parts/amass/go/src/github.com/OWASP/Amass/amass/dnssrv/wildcards.go:71 +0x90
github.com/OWASP/Amass/amass/dnssrv.DetectWildcard(0x7ffe9942d398, 0xb, 0xc435df8440, 0x15, 0xc4596f8030, 0x1, 0x1, 0x0)
        /go/src/github.com/OWASP/Amass/parts/amass/go/src/github.com/OWASP/Amass/amass/dnssrv/wildcards.go:34 +0x12e
github.com/OWASP/Amass/amass/dnssrv.(*DNSService).completeQueries(0xc4200d8370, 0xc439e66ae0)
        /go/src/github.com/OWASP/Amass/parts/amass/go/src/github.com/OWASP/Amass/amass/dnssrv/dnssrv.go:160 +0x3e2
created by github.com/OWASP/Amass/amass/dnssrv.(*DNSService).performRequest
        /go/src/github.com/OWASP/Amass/parts/amass/go/src/github.com/OWASP/Amass/amass/dnssrv/dnssrv.go:119 +0x13a
```

I'm getting something like this a lot of these lately, crashing the execution of amass. No idea what's causing it. It's been happening alot the last few days though.

**Comment by caffix** [comment]
Did it say why the wait caused a program crash?

**Comment by CharlieEriksen** [comment]
Nope, the terminal output is so long that it's nowhere to be found

**Comment by caffix** [comment]
@CharlieEriksen I believe I've hunted down the source of this problem and started to fix it. Can you still reproduce these errors with version 2.7.10+?

**Comment by caffix** [comment]
I have not heard or seen anything lately about this being an issue, so I'm going to close it now.
