### ISSUE TITLE
intel subcommand can't run

### ISSUE THREAD

**Issue by Rvn0xsy** [OWASP/Amass#292]
```
root@kali:~# amass intel -whois -active -ip -src -p 80 -d example.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa61b36]

goroutine 37 [running]:
github.com/OWASP/Amass/resolvers.(*ResolverPool).numUsableResolvers(0x0, 0xc00000e7c0)
	/build/amass-QlKQKB/amass-3.1.8/resolvers/pool.go:413 +0x26
github.com/OWASP/Amass/resolvers.(*ResolverPool).Resolve(0x0, 0x104c6b7, 0xe, 0x103e798, 0x1, 0x1, 0x4584f0, 0xc000179e10, 0xc000179e18, 0x8, ...)
	/build/amass-QlKQKB/amass-3.1.8/resolvers/pool.go:226 +0x40
github.com/OWASP/Amass/services/sources.(*RADb).OnStart(0xc0013981c0, 0x14de200, 0xc0013981c0)
	/build/amass-QlKQKB/amass-3.1.8/services/sources/radb.go:60 +0x6b
github.com/OWASP/Amass/services.(*BaseService).Start(0xc0013981c0, 0x0, 0x0)
	/build/amass-QlKQKB/amass-3.1.8/services/service.go:173 +0x17f
github.com/OWASP/Amass/intel.(*Collection).ReverseWhois(0xc00097a4e0, 0x0, 0x0)
	/build/amass-QlKQKB/amass-3.1.8/intel/intel.go:360 +0x1fa
created by main.runIntelCommand
	/build/amass-QlKQKB/amass-3.1.8/cmd/amass/intel.go:216 +0xca9
root@kali:~# 
```

**Comment by Rvn0xsy** [comment]
#276

**Comment by Rvn0xsy** [comment]
Now the version installed by kali Linux apt-get install amass is still 3.1.8, I hope to update to the kali source as soon as possible.

**Comment by Rvn0xsy** [comment]
root@kali:/usr/share/amass# apt search amass
Sorting... Done
Full Text Search... Done
amass/kali-rolling,now 3.1.8-0kali1 amd64 [installed]
  In-depth DNS Enumeration and Network Mapping

amass-common/kali-rolling,now 3.1.8-0kali1 all [installed,automatic]
  In-depth DNS Enumeration and Network Mapping
