### ISSUE TITLE
intel -whois leads to nil pointer (kali linux)

### ISSUE THREAD

**Issue by dkberlin** [OWASP/Amass#324]
using v 3.1.8, might this be the problem? if so, how to update?

```
[2019-11-14 15:06:44]  ~ > amass intel -whois -d volkswagen.de
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa61b36]

goroutine 21 [running]:
github.com/OWASP/Amass/resolvers.(*ResolverPool).numUsableResolvers(0x0, 0xc0009444a0)
	/build/amass-QlKQKB/amass-3.1.8/resolvers/pool.go:413 +0x26
github.com/OWASP/Amass/resolvers.(*ResolverPool).Resolve(0x0, 0x104c6b7, 0xe, 0x103e798, 0x1, 0x1, 0x4584f0, 0xc001729e10, 0xc001729e18, 0x8, ...)
	/build/amass-QlKQKB/amass-3.1.8/resolvers/pool.go:226 +0x40
github.com/OWASP/Amass/services/sources.(*RADb).OnStart(0xc000126ee0, 0x14de200, 0xc000126ee0)
	/build/amass-QlKQKB/amass-3.1.8/services/sources/radb.go:60 +0x6b
github.com/OWASP/Amass/services.(*BaseService).Start(0xc000126ee0, 0x0, 0x0)
	/build/amass-QlKQKB/amass-3.1.8/services/service.go:173 +0x17f
github.com/OWASP/Amass/intel.(*Collection).ReverseWhois(0xc000956480, 0x0, 0x0)
	/build/amass-QlKQKB/amass-3.1.8/intel/intel.go:360 +0x1fa
created by main.runIntelCommand
	/build/amass-QlKQKB/amass-3.1.8/cmd/amass/intel.go:216 +0xca9
```

**Comment by dkberlin** [comment]
edit: updated to the latest version. all good now.

**Comment by caffix** [comment]
The Kali Linux Amass package is in the process of being updated as well. Thank you!
