### ISSUE TITLE
amass not working after installation

### ISSUE THREAD

**Issue by tmdh** [OWASP/Amass#347]
I just installed amass. I wanted to run `amass enum --passive -d domain.com`. But it's showing me an error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xacd83c]

goroutine 517 [running]:
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:48
github.com/OWASP/Amass/v3/graph/db.(*CayleyGraph).AllNodesOfType(0x0, 0x11204d5, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/tareque/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.4.2/graph/db/cayley.go:167 +0x5c
github.com/OWASP/Amass/v3/graph.(*Graph).EventList(0xc000192870, 0xc000190088, 0x1, 0x1)
        /home/tareque/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.4.2/graph/event.go:113 +0x6e
github.com/OWASP/Amass/v3/enum.(*Enumeration).submitKnownNames(0xc0000a4000, 0xc0002f8580)
        /home/tareque/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.4.2/enum/io.go:26 +0x230
created by github.com/OWASP/Amass/v3/enum.(*Enumeration).Start
        /home/tareque/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.4.2/enum/enum.go:191 +0x4f6
```

```
tareque@DELL:/mnt/c/Users/Tareque/linux$ amass -version
v3.4.2
tareque@DELL:/mnt/c/Users/Tareque/linux$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tareque/.cache/go-build"
GOENV="/home/tareque/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tareque/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build603623396=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by caffix** [comment]
@tmdh What method of installation did you choose?

Also, try deleting the default output directory in the case that you have an older database being read by a newer version of the tool

**Comment by tmdh** [comment]
I installed `amass` from source code.

```
go get -v -u github.com/OWASP/Amass/v3/...
```

**Comment by caffix** [comment]
Please try a prebuilt binary and see if you still experience the same problem

**Comment by tmdh** [comment]
I still experience the same problem.

```
tareque@DELL:/mnt/c/Users/Tareque/linux/amass$ ./amass enum --passive -d pubg.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xab210c]

goroutine 506 [running]:
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:48
github.com/OWASP/Amass/v3/graph/db.(*CayleyGraph).AllNodesOfType(0x0, 0x10f5066, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/caffix/go/src/github.com/OWASP/Amass/graph/db/cayley.go:167 +0x5c
github.com/OWASP/Amass/v3/graph.(*Graph).EventList(0xc0001b3ad0, 0xc00000e6c0, 0x1, 0x1)
        /home/caffix/go/src/github.com/OWASP/Amass/graph/event.go:113 +0x6e
github.com/OWASP/Amass/v3/enum.(*Enumeration).submitKnownNames(0xc000152000, 0xc000638960)
        /home/caffix/go/src/github.com/OWASP/Amass/enum/io.go:26 +0x230
created by github.com/OWASP/Amass/v3/enum.(*Enumeration).Start
        /home/caffix/go/src/github.com/OWASP/Amass/enum/enum.go:191 +0x4f6
```

**Comment by caffix** [comment]
@tmdh Please see if this is still giving you trouble. Thank you!

**Comment by szytko** [comment]
@caffix I'm using Amass in one of my golang project running in AWS Lambda and getting the same error 

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd48cdc]
goroutine 2020 [running]:
github.com/OWASP/Amass/v3/graph/db.(*CayleyGraph).AllNodesOfType(0x0, 0x12ad4fe, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
github.com/OWASP/Amass/v3@v3.5.4/graph/db/cayley.go:170 +0x5c
github.com/OWASP/Amass/v3/graph.(*Graph).EventList(0xc0003308d0, 0xc00000e0e8, 0x1, 0x1)
github.com/OWASP/Amass/v3@v3.5.4/graph/event.go:122 +0x6e
github.com/OWASP/Amass/v3/enum.(*Enumeration).submitKnownNames(0xc0002ce8c0)
github.com/OWASP/Amass/v3@v3.5.4/enum/io.go:20 +0xa9
created by github.com/OWASP/Amass/v3/enum.(*Enumeration).Start
github.com/OWASP/Amass/v3@v3.5.4/enum/enum.go:197 +0x78c
2020/04/03 11:38:07 unexpected EOF
2020/04/03 11:38:07 unexpected EOF
```
any idea what may cause this ?

@tmdh did you find a solution for that ?

**Comment by tmdh** [comment]
@caffix It was not working because I was trying amass in WSL (Windows Subsystem for Linux) which is not very stable. It worked fine in a normal Ubuntu machine and a Windows machine. I am closing this issue.

**Comment by x1sec** [comment]
Can confirm the same issue exists when running in WSL:
```
amass enum -d <REDACTED>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x95caac]

goroutine 79 [running]:
github.com/OWASP/Amass/v3/graph/db.(*CayleyGraph).AllNodesOfType(0x0, 0xf5f0c7, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/user/go/src/github.com/OWASP/Amass/graph/db/cayley.go:170 +0x5c
github.com/OWASP/Amass/v3/graph.(*Graph).EventList(0xc0005942a0, 0xc00059e028, 0x1, 0x1)
        /home/user/go/src/github.com/OWASP/Amass/graph/event.go:122 +0x6e
github.com/OWASP/Amass/v3/enum.(*Enumeration).submitKnownNames(0xc000236380)
        /home/user/go/src/github.com/OWASP/Amass/enum/io.go:20 +0xa9
created by github.com/OWASP/Amass/v3/enum.(*Enumeration).Start
        /home/user/go/src/github.com/OWASP/Amass/enum/enum.go:197 +0x78c
```

**Comment by tmdh** [comment]
@x1sec Wait for WSL2 to come out. Then try again. I don't think it's amass's issue.

**Comment by caffix** [comment]
I can see from the panic provided by @x1sec what the problem is likely to be. In WSL, amass is not being allowed to create the graph database in the output directory. This problem has come up in some Linux distributions that are popular when using Docker.

It could be due to amass not being able to find the default output directory location within WSL. I would try assigning your own location by using the `-dir` flag
