### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xyele** [OWASP/Amass#369]
Hey, I'm getting this error at Ubuntu WSL with released amd64 binary. Could anyone please help?

```
xyele@DESKTOP:~/thirdparty$ ./amass enum -d uber.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa09f8c]

goroutine 515 [running]:
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:48
github.com/OWASP/Amass/v3/graph/db.(*CayleyGraph).AllNodesOfType(0x0, 0x104aad7, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/caffix/go/src/github.com/OWASP/Amass/graph/db/cayley.go:170 +0x5c
github.com/OWASP/Amass/v3/graph.(*Graph).EventList(0xc00021b2f0, 0xc0000d02d0, 0x1, 0x1)
        /Users/caffix/go/src/github.com/OWASP/Amass/graph/event.go:122 +0x6e
github.com/OWASP/Amass/v3/enum.(*Enumeration).submitKnownNames(0xc00026a000, 0xc0005c8350)
        /Users/caffix/go/src/github.com/OWASP/Amass/enum/io.go:26 +0x230
created by github.com/OWASP/Amass/v3/enum.(*Enumeration).Start
        /Users/caffix/go/src/github.com/OWASP/Amass/enum/enum.go:191 +0x4f6
```

Also, Intel module works for me.

reference issues
https://github.com/OWASP/Amass/issues/276

**Comment by caffix** [comment]
We do not guarantee success with WSL, but out of curiosity, what version of Amass did you use?

**Comment by xyele** [comment]
v3.4.4
