### ISSUE TITLE
segfault when enumerating

### ISSUE THREAD

**Issue by hazcod** [OWASP/Amass#387]
Amass go library v3.5.4 , using on docker. (static go compile to scratch image)

Code:
```go
	cfg := config.NewConfig()
	cfg.AddDomain(domain.Name)
	cfg.BruteForcing  = bruteforce
	cfg.Alterations   = permute
	cfg.Blacklist     = domain.Blacklisted
	cfg.Active		  = !passive
	cfg.Passive		  = passive
	cfg.ProvidedNames = domain.Whitelisted
	cfg.Log 		  = zap.NewStdLog(logger)
	cfg.Verbose 	  = log.IsLevelEnabled(log.DebugLevel)
	cfg.Resolvers	  = defaultResolvers

	if err := cfg.CheckSettings(); err != nil {
		return nil, errors.Wrap(err, "invalid amass config")
	}

	sys, err := services.NewLocalSystem(cfg)
	if err != nil {
		return nil, errors.Wrap(err, "could not create local system")
	}

	enumerator := enum.NewEnumeration(sys)
	if enumerator == nil {
		return nil, errors.Wrap(err, "could not create enumeration")
	}
	enumerator.Config = cfg

	finished := make(chan struct{})
	go func() {
		logger.Debug("capturing output")
		for out := range enumerator.Output {
			logger.Debug("found enumerated domain", zap.String("name", out.Name), zap.String("domain", out.Name))

			domainResult := EnumerateDomainResult{
				Domain: out.Domain,
				Name:   out.Name,
				Source: out.Source,
			}

			for _, addr := range out.Addresses {
				domainResult.Addresses = append(domainResult.Addresses, DomainAddress{
					Address:     addr.Address.String(),
					ASN:         strconv.Itoa(addr.ASN),
					Description: addr.Description,
				})
			}

			results = append(results, domainResult)
		}
		close(finished)
	}()

	logger.Debug("starting enumerator")
	if err := enumerator.Start(); err != nil {
		return nil, errors.Wrap(err, "could not start enumerator")
	}

	<- finished
```

Log:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe1defd]


goroutine 232 [running]:

sync.(*Mutex).Lock(...)

/usr/local/go/src/sync/mutex.go:74

github.com/hazcod/securitytxt/vendor/github.com/OWASP/Amass/v3/graph/db.(*CayleyGraph).AllNodesOfType(0x0, 0x1447439, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

/go/src/github.com/hazcod/securitytxt/vendor/github.com/OWASP/Amass/v3/graph/db/cayley.go:170 +0x5d

github.com/hazcod/securitytxt/vendor/github.com/OWASP/Amass/v3/graph.(*Graph).EventList(0xc00031d710, 0xc00034e108, 0x1, 0x1)

/go/src/github.com/hazcod/securitytxt/vendor/github.com/OWASP/Amass/v3/graph/event.go:122 +0x6e

github.com/hazcod/securitytxt/vendor/github.com/OWASP/Amass/v3/enum.(*Enumeration).submitKnownNames(0xc000174540)

/go/src/github.com/hazcod/securitytxt/vendor/github.com/OWASP/Amass/v3/enum/io.go:20 +0xa9

created by github.com/hazcod/securitytxt/vendor/github.com/OWASP/Amass/v3/enum.(*Enumeration).Start

/go/src/github.com/hazcod/securitytxt/vendor/github.com/OWASP/Amass/v3/enum/enum.go:197 +0x78c
```

**Comment by hazcod** [comment]
This does not seem to happen if I run as root under alpine. Ideas why?

**Comment by caffix** [comment]
Perhaps the default location for the output directory and graph database on Alpine require root privileges to create. I can add more error checking for this. You could also set your output directory to another location if you'd like to execute the code without the root privileges

**Comment by hazcod** [comment]
@catfix: are the output directory and graph database required?

**Comment by caffix** [comment]
At this point in time, yes, the output directory and graph database are not optional

**Comment by hazcod** [comment]
Can confirm it works with 
```go
	tempDir, err := ioutil.TempDir(os.TempDir(), "amass")
	if err != nil {
		logger.With(zap.Error(err)).Error("could not create temp dir")
		return nil, err
	}
	logger = logger.With(zap.String("temp_dir", tempDir))
	defer os.RemoveAll(tempDir)

	cfg.Dir			  = tempDir
```

**Comment by caffix** [comment]
We appreciate the useful feedback
