### ISSUE TITLE
Asn lookup causes panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by mrthankyou** [OWASP/Amass#389]
When running `amass intel -asn [insert ASN here]` on MacOS 10.14.6 I get the following output in my terminal:

```
goroutine 467 [running]:
github.com/OWASP/Amass/v3/stringset.Set.Insert(...)
	/Users/caffix/go/src/github.com/OWASP/Amass/stringset/set.go:39
github.com/OWASP/Amass/v3/stringset.Set.Union(0x0, 0xc004f0ecc0)
	/Users/caffix/go/src/github.com/OWASP/Amass/stringset/set.go:75 +0xaa
github.com/OWASP/Amass/v3/services.(*NetworksDB).executeAPIASNQuery(0xc004ea0750, 0x2068a40, 0xc0002de540, 0x57ee, 0x0, 0x0, 0x0)
	/Users/caffix/go/src/github.com/OWASP/Amass/services/networksdb.go:303 +0x5bb
github.com/OWASP/Amass/v3/services.(*NetworksDB).OnASNRequest(0xc004ea0750, 0x2068a40, 0xc0002de540, 0xc004f0a460)
	/Users/caffix/go/src/github.com/OWASP/Amass/services/networksdb.go:95 +0x19a
reflect.Value.call(0x1ab9f80, 0xc004f0c2a0, 0x13, 0x1c4918b, 0x4, 0xc0001d0f90, 0x2, 0x2, 0xc000353728, 0x1005e7a, ...)
	/usr/local/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x1ab9f80, 0xc004f0c2a0, 0x13, 0xc0001d0f90, 0x2, 0x2, 0xc0003537b8, 0x171a979, 0x2078380)
	/usr/local/go/src/reflect/value.go:321 +0xb4
github.com/OWASP/Amass/v3/services.(*BaseService).processRequests(0xc004ea0750)
	/Users/caffix/go/src/github.com/OWASP/Amass/services/service.go:307 +0x199
created by github.com/OWASP/Amass/v3/services.(*BaseService).Start
	/Users/caffix/go/src/github.com/OWASP/Amass/services/service.go:135 +0xf8
```

Current amass version is v3.4.4. When reviewing the amass log file I see the following which is to be expected since I didn't provide API keys for these services:

```
13:21:33.866924 CIRCL: API key data was not provided
13:21:34.517106 PassiveTotal: API key data was not provided
13:21:34.733930 Twitter: API key data was not provided
13:21:34.733985 Umbrella: API key data was not provided
13:21:34.734034 WhoisXML: API key data was not provided
```

Finally, when running something like `amass intel -org` everything works fine. 

Question: How can this be resolved? Thanks for the time and help.

**Comment by caffix** [comment]
Please start the troubleshooting process by bringing Amass to the most current version (v3.5.4)
