### ISSUE TITLE
Failed to create the Cayley Graph graph Ubuntu WSL

### ISSUE THREAD

**Issue by Handerllon** [OWASP/Amass#416]
Hi!

Im having some trouble running amass in Ubuntu WSL 18.04.

At first I had version `v3.4.2` and, when running `amass enum -d tesla.com` I got the following error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xab210c]

goroutine 471 [running]:
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:48
github.com/OWASP/Amass/v3/graph/db.(*CayleyGraph).AllNodesOfType(0x0, 0x10f5066, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/caffix/go/src/github.com/OWASP/Amass/graph/db/cayley.go:167 +0x5c
github.com/OWASP/Amass/v3/graph.(*Graph).EventList(0xc000159440, 0xc00000e770, 0x1, 0x1)
        /home/caffix/go/src/github.com/OWASP/Amass/graph/event.go:113 +0x6e
github.com/OWASP/Amass/v3/enum.(*Enumeration).submitKnownNames(0xc000166b60, 0xc0001d3804)
        /home/caffix/go/src/github.com/OWASP/Amass/enum/io.go:26 +0x230
created by github.com/OWASP/Amass/v3/enum.(*Enumeration).Start
``` 

After searching the issues, I saw a possible fix was to update to the latest version.

Using the same command with version `v3.6.3 amd 64 binary` I get the following

`System: Failed to create the Cayley Graph graph`

Thanks for the help!

**Comment by caffix** [comment]
There's no official support for Ubuntu WSL, and it has caused problems for users. From the error message you shared, I recommend providing your own output directory via the `-dir` flag
