### ISSUE TITLE
[Bug] Panic: send on closed channel

### ISSUE THREAD

**Issue by ColdBrewed** [OWASP/Amass#44]
Getting consistent failures with the following scan:
`amass -v -ip -brute -min-for-recursive 6 -df domains.txt -oA resultsFile`

error message:
`panic: send on closed channel
goroutine 8652393 [running]:
github.com/caffix/amass/amass.StartEnumeration.func1(0xc551ca7a40)                           
        /home/caffix/go_work/src/github.com/caffix/amass/amass/amass.go:63 +0x42             
reflect.Value.call(0x88b940, 0xc42002e080, 0x13, 0x938ef4, 0x4, 0xc46b4080e0, 0x1, 0x1, 0xc551ca7a40, 0xc4a8aa3900, ...)
        /usr/local/go/src/reflect/value.go:447 +0x969                                        
reflect.Value.Call(0x88b940, 0xc42002e080, 0x13, 0xc46b4080e0, 0x1, 0x1, 0xc46b4080e0, 0x1, 0x1)
        /usr/local/go/src/reflect/value.go:308 +0xa4                                         
github.com/asaskevich/EventBus.(*EventBus).doPublish(0xc4203f0060, 0xc42044a0f0, 0x93f5f9, 0xc, 0xc4a8aa3900, 0x1, 0x1)
        /home/caffix/go_work/src/github.com/asaskevich/EventBus/event_bus.go:158 +0xa8       
github.com/asaskevich/EventBus.(*EventBus).doPublishAsync(0xc4203f0060, 0xc42044a0f0, 0x93f5f9, 0xc, 0xc4a8aa3900, 0x1, 0x1)
        /home/caffix/go_work/src/github.com/asaskevich/EventBus/event_bus.go:166 +0xa3       
created by github.com/asaskevich/EventBus.(*EventBus).Publish                                
        /home/caffix/go_work/src/github.com/asaskevich/EventBus/event_bus.go:150 +0x28b `

Binary version 2.8.0

**Comment by caffix** [comment]
Thank you, @ColdBrewed, yet no Amass binaries have been provided for Amass version 2.8.0 yet. Perhaps it would be best if you rebuilt/reinstalled it first to solve this problem. Which operation system are you installing it on?

**Comment by ColdBrewed** [comment]
Thanks for the quick response @caffix. I was using the 2.5.2 linux amd64 prebuilt image. Trying again with 2.8.0 and the snap installation method. 

I'm running this on Kali rolling.

**Comment by caffix** [comment]
Is everything working smoothly for you now, @ColdBrewed?

**Comment by caffix** [comment]
Thank you, @ColdBrewed.
