### ISSUE TITLE
Running amass based on solely the config file gives no output and errors out.

### ISSUE THREAD

**Issue by adi928** [OWASP/Amass#513]
Hi, I've been working with amass with all the cmd arguments. I wanted to make a switch to using the configuration files as it is easier to maintain and share. 
I'm trying to run `amass enum -config config.ini` with the following ini file: https://gist.github.com/adi928/dabe2d07099c5fcbcb86a595066c41b1

I see the folder being created, but empty amass.txt and amass.json. The amass.log contains failed connection attempts at unused APIs. And I get the following (possibly) error messages in the terminal.

```
/home/caffix/go/src/github.com/OWASP/Amass/resolvers/wildcards.go:142 +0x17e
created by github.com/OWASP/Amass/v3/resolvers.NewBaseResolver
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:171 +0x485

goroutine 108 [select]:
github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).sendQueries(0xc003d447e0)
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:397 +0xf5
created by github.com/OWASP/Amass/v3/resolvers.NewBaseResolver
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:172 +0x4a7

goroutine 109 [select]:
github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).checkForTimeouts(0xc003d447e0)
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:338 +0x4ae
created by github.com/OWASP/Amass/v3/resolvers.NewBaseResolver
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:173 +0x4c9

goroutine 110 [IO wait]:
internal/poll.runtime_pollWait(0x7f51c7e00958, 0x72, 0x1b08020)
        /usr/local/go/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc0000db218, 0x72, 0xc003ffe000, 0x1000, 0x1000)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000db200, 0xc003ffe000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:159 +0x1b1
net.(*netFD).Read(0xc0000db200, 0xc003ffe000, 0x1000, 0x1000, 0xc003d40dc8, 0x40b64a, 0x10aa520)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00000e1e0, 0xc003ffe000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:182 +0x8e
github.com/miekg/dns.(*Conn).Read(0xc028b58150, 0xc003ffe000, 0x1000, 0x1000, 0xc00000e1e0, 0xc003d40e01, 0x4d9fba)
        /home/caffix/go/pkg/mod/github.com/miekg/dns@v1.1.31/client.go:276 +0x235
github.com/miekg/dns.(*Conn).ReadMsgHeader(0xc028b58150, 0x0, 0x3cd34e4ee, 0x22a3760, 0xc0000db200, 0x19fc1b0, 0xc003d40f70)
        /home/caffix/go/pkg/mod/github.com/miekg/dns@v1.1.31/client.go:240 +0xca
github.com/miekg/dns.(*Conn).ReadMsg(0xc028b58150, 0xbfe32f47db4ac0ea, 0x3cd34e4ee, 0x22a3760)
        /home/caffix/go/pkg/mod/github.com/miekg/dns@v1.1.31/client.go:202 +0x49
github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).readMessages(0xc003d447e0, 0xc003d1b800)
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:435 +0xc9
created by github.com/OWASP/Amass/v3/resolvers.NewBaseResolver
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:174 +0x4f0

goroutine 111 [chan receive]:
github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).lastConnection(0xc003d447e0, 0xc003d30d20)
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver_state.go:432 +0xc5
github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).readMessages(0xc003d447e0, 0xc003d1b801)
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:428 +0x65
created by github.com/OWASP/Amass/v3/resolvers.NewBaseResolver
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:175 +0x517

goroutine 112 [select]:
github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).processReadMessages(0xc003d447e0)
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:449 +0xf5
created by github.com/OWASP/Amass/v3/resolvers.NewBaseResolver
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:176 +0x539

goroutine 114 [select]:
github.com/OWASP/Amass/v3/resolvers.(*ResolverPool).manageDomainCache(0xc003d465a0, 0xc003d44840)
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/pool.go:195 +0x425
created by github.com/OWASP/Amass/v3/resolvers.NewResolverPool
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/pool.go:105 +0x1d3
```

What am I missing from the config file or the command-line argument?

**Comment by caffix** [comment]
I should be able to help if you capture the entire crash dump

**Comment by adi928** [comment]
CPU memory was identified to be the issue. Amass was running out of space. Closing this issue.
