### ISSUE TITLE
unexpected fault address 0x2cb30000 fatal error: fault [signal SIGSEGV: segmentation violation code=0x1

### ISSUE THREAD

**Issue by storenth** [OWASP/Amass#520]
Unexpected crash while run the next script:
```bash
sudo amass enum -brute -min-for-recursive 10 -rf ./resolvers/mini_resolvers.txt -max-dns-queries 7000 -log amass.log -d zakazaka.ru -o ./amass-list.txt &> amass_error_log.log
```
I reproduced this case with `-brute -min-for-recursive 2 -max-dns-queries 500` arguments, failed too. I need help, please suggest workaround or fix.
I think failed on the last step "Discoveries are being migrated into the local database"! Original log ~100Mb, so I simplify it by removing duplicated lines 
[amass_error_log_small.txt](https://github.com/OWASP/Amass/files/5685254/amass_error_log_small.txt):
```bash
unexpected fault address 0x2cb30000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2cb30000 pc=0x1844cff]

goroutine 271 [running]:
runtime.throw(0x1d94328, 0x5)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc01d2c52c0 sp=0xc01d2c5290 pc=0x1035832
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:727 +0x3e5 fp=0xc01d2c52f0 sp=0xc01d2c52c0 pc=0x104b665
github.com/boltdb/bolt.(*DB).page(...)
        /home/caffix/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:796
github.com/boltdb/bolt.(*Tx).page(...)
---
github.com/OWASP/Amass/v3/graph.(*Graph).EventNames(0xc0118d20c0, 0xc00bb49aa0, 0x24, 0x27108e0, 0xc000626000, 0x1, 0x1, 0x80)
        /home/caffix/go/src/github.com/OWASP/Amass/graph/io.go:99 +0x8c fp=0xc01d2c5ed0 sp=0xc01d2c5e10 pc=0x192664c
github.com/OWASP/Amass/v3/enum.(*Enumeration).submitKnownNames(0xc000f7e000)
        /home/caffix/go/src/github.com/OWASP/Amass/enum/io.go:46 +0x3b1 fp=0xc01d2c5fd8 sp=0xc01d2c5ed0 pc=0x1b0fa71
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc01d2c5fe0 sp=0xc01d2c5fd8 pc=0x106b001
created by github.com/OWASP/Amass/v3/enum.(*Enumeration).Start
        /home/caffix/go/src/github.com/OWASP/Amass/enum/enum.go:227 +0x5c5
goroutine 1 [panicwait]:
runtime.gopark(0x0, 0x0, 0xc000091008, 0x1)
        /usr/local/go/src/runtime/proc.go:306 +0xe5
runtime.main()
        /usr/local/go/src/runtime/proc.go:223 +0x285
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1

goroutine 42 [select]:
io.(*pipe).Read(0xc0002807e0, 0xc00027c2ae, 0xd52, 0xd52, 0x2e7ada0, 0xc02a5a9500, 0x2)
        /usr/local/go/src/io/pipe.go:57 +0xe7
io.(*PipeReader).Read(0xc00028c518, 0xc00027c2ae, 0xd52, 0xd52, 0x10f5037, 0xc0010644e0, 0xc003dba080)
        /usr/local/go/src/io/pipe.go:134 +0x4c
bufio.(*Scanner).Scan(0xc00009ef20, 0x2706160)
        /usr/local/go/src/bufio/scan.go:214 +0xa9
main.writeLogsAndMessages(0xc00028c518, 0x7ffeefbffa56, 0x9, 0x3184100)
        /home/caffix/go/src/github.com/OWASP/Amass/cmd/amass/enum.go:559 +0x1de
created by main.runEnumCommand
        /home/caffix/go/src/github.com/OWASP/Amass/cmd/amass/enum.go:170 +0x41f
```
### Environment:
```bash
$ uname -r && amass -version && go version             
19.6.0
v3.10.5
go version go1.15.3 darwin/amd64
```
### Resolvers

<img width="443" alt="Снимок экрана 2020-12-14 в 01 28 28" src="https://user-images.githubusercontent.com/18244131/102021553-225ea380-3db3-11eb-9691-d23423ece41f.png">

### Preference:
```bash
ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2784
-n: file descriptors                10496
```
<img width="979" alt="Снимок экрана 2020-12-14 в 02 07 56" src="https://user-images.githubusercontent.com/18244131/102021468-8e8cd780-3db2-11eb-99fd-cbeba4543443.png">

**Comment by caffix** [comment]
Are you still experiencing this with the latest version of Amass?

**Comment by storenth** [comment]
Sorry, no I don't. I disable amass from my flow.
