### ISSUE TITLE
panic on enum on v3.10.5

### ISSUE THREAD

**Issue by hazcod** [OWASP/Amass#525]
```
 % amass enum -d twegos.com -brute -active
Querying Riddler for twegos.com subdomains
Querying BufferOver for twegos.com subdomains
assessment.twegos.com
www.twegos.com
Querying UKGovArchive for twegos.com subdomains
Querying AlienVault for twegos.com subdomains
Querying Ask for twegos.com subdomains
Querying Pastebin for twegos.com subdomains
Querying URLScan for twegos.com subdomains
Average DNS queries performed: 291/sec, Average retries required: 11.68%
Querying GoogleCT for twegos.com subdomains
Querying DNSDumpster for twegos.com subdomains
Querying BuiltWith for twegos.com subdomains
Querying HackerTarget for twegos.com subdomains
Querying SiteDossier for twegos.com subdomains
Querying Brute Forcing for twegos.com subdomains
Querying CommonCrawl for twegos.com subdomains
Querying HackerOne for twegos.com subdomains
Querying LoCArchive for twegos.com subdomains
Querying Crtsh for twegos.com subdomains
Querying ViewDNS for twegos.com subdomains
Average DNS queries performed: 16/sec, Average retries required: 0.00%
Querying Yahoo for twegos.com subdomains
Querying Mnemonic for twegos.com subdomains
customers.twegos.com
localhost.twegos.com
stagingrecruit.twegos.com
newwidget.twegos.com
newassessment.twegos.com
landing.twegos.com
new.twegos.com
widget.twegos.com
stagingmatch.twegos.com
newclientcenter.twegos.com
ftp.twegos.com
ssh.twegos.com
stagingwww.twegos.com
stagingwidget.twegos.com
stagingassessment.twegos.com
staff.twegos.com
clientcenter.twegos.com
stagingclientcenter.twegos.com
demo.twegos.com
staginglanding.twegos.com
Querying Baidu for twegos.com subdomains
recruit.twegos.com
match.twegos.com
Querying VirusTotal for twegos.com subdomains
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x19b2cb6]

goroutine 35270 [running]:
github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).tcpExchange(0xc00003bda0, 0x39ba947, 0xc0074f49b0)
	/home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:517 +0x56
created by github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).processMessage
	/home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:482 +0x519
```

**Comment by phackt** [comment]
Hi, i was about to open the same issue, i'm building a docker image like this:
```
docker build -t amass https://github.com/OWASP/Amass.git
```
  
When running the following command:
```
amass enum -active -p 443 -src -norecursive -brute -w /wordlists/subdomains.txt -json /output/redacted.json -d redacted.com
```
  
I also have this error:
```
...
[2020-12-24 17:42:17,845] {docker_operator.py:243} INFO - Querying BufferOver for redacted.com subdomains
[2020-12-24 17:42:22,087] {docker_operator.py:243} INFO - panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xdbb1f6]

goroutine 979727 [running]:
[2020-12-24 17:42:22,088] {docker_operator.py:243} INFO - github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).tcpExchange(0xc00093a240, 0x64ce77, 0xc02a2c3400)
	/go/src/github.com/OWASP/Amass/resolvers/resolver.go:517 +0x56
created by github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).processMessage
	/go/src/github.com/OWASP/Amass/resolvers/resolver.go:482 +0x519

```

I think there are several people having the same issue right now.

Regards,

**Comment by Viss** [comment]
I'm also having this exact same issue.

**Comment by caffix** [comment]
This has been brought up in another issue
