### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xothkug** [OWASP/Amass#528]
Every time i run "amass enum -d oppo.com " I get,

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xdcbef6]


goroutine 325257 [running]:
github.com/OWASP/Amass/resolvers.(*BaseResolver).tcpExchange(0xc0001ba480, 0x2c3471, 0xc02564c000)
        /home/groeneappel/go/src/github.com/OWASP/Amass/resolvers/resolver.go:517 +0x56
created by github.com/OWASP/Amass/resolvers.(*BaseResolver).processMessage
        /home/groeneappel/go/src/github.com/OWASP/Amass/resolvers/resolver.go:482 +0x519

```

Ive tried dns-max-queries 200 but same thing. Am i doing something wrong?

**Comment by caffix** [comment]
This problem has been addressed in issue #519
