### ISSUE TITLE
[Bug]: panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by ZeroDot1** [OWASP/Amass#543]
`'/bin/amass' enum -config '/config.ini' -passive -d poolvale.ddns.net`

```go
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xe7d9fe]

goroutine 3518 [running]:
github.com/yuin/gopher-lua.(*LState).PCall.func1(0x1a017c0, 0xc0004606e0, 0xc01fe379c0, 0x0, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2012 +0x11e
panic(0x1015700, 0x225a090)
	/usr/lib/go/src/runtime/panic.go:969 +0x1b9
github.com/yuin/gopher-lua.callGFunction(0xc0004606e0, 0x0, 0xc0022d8000)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:262 +0x1f7
github.com/yuin/gopher-lua.init.3.func26(0xc0004606e0, 0xc07c200203, 0xc0023c0000, 0x0)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:817 +0x39d
github.com/yuin/gopher-lua.mainLoop(0xc0004606e0, 0xc0023c0000)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:31 +0xf4
github.com/yuin/gopher-lua.(*LState).callR(0xc0004606e0, 0x2, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1203 +0x256
github.com/yuin/gopher-lua.(*LState).Call(...)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1959
github.com/yuin/gopher-lua.(*LState).PCall(0xc0004606e0, 0x2, 0x0, 0x0, 0x1b07940, 0xc0106e9f00)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2022 +0x114
github.com/yuin/gopher-lua.(*LState).CallByParam(0xc0004606e0, 0x1b20e40, 0xc0022d8e80, 0x0, 0x1, 0x0, 0xc003266a78, 0x2, 0x2, 0x1b1e700, ...)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2040 +0xe9
github.com/OWASP/Amass/v3/datasrcs.(*Script).dnsRequest(0xc0002ab2c0, 0x1b1e700, 0xc00e4d9470, 0xc00341cba0)
	/home/user/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.11.1/datasrcs/script.go:289 +0x35b
github.com/OWASP/Amass/v3/datasrcs.(*Script).OnRequest(0xc0002ab2c0, 0x1b1e700, 0xc00e4d9470, 0x1032620, 0xc00341cba0)
	/home/user/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.11.1/datasrcs/script.go:259 +0x113
reflect.Value.call(0xfd2f00, 0xc00ba0f5c0, 0x13, 0x1175a1b, 0x4, 0xc00e526330, 0x2, 0x2, 0x8c29f40fa, 0x228a1c0, ...)
	/usr/lib/go/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0xfd2f00, 0xc00ba0f5c0, 0x13, 0xc00e526330, 0x2, 0x2, 0x0, 0x1, 0xc000ee86a0)
	/usr/lib/go/src/reflect/value.go:337 +0xb9
github.com/caffix/service.(*BaseService).processRequests.func1(0xf8c9a0, 0xc00e526360)
	/home/user/go/pkg/mod/github.com/caffix/service@v0.0.0-20210101222658-354b1fdf7f24/base.go:166 +0x1d5
github.com/caffix/queue.(*queue).Process(0xc00a4e4990, 0xc00323e200)
	/home/user/go/pkg/mod/github.com/caffix/queue@v0.0.0-20210106184330-1d2e72b64fa0/queue.go:172 +0x4f
github.com/caffix/service.(*BaseService).processRequests(0xc0002ab2c0)
	/home/user/go/pkg/mod/github.com/caffix/service@v0.0.0-20210101222658-354b1fdf7f24/base.go:175 +0x92
created by github.com/caffix/service.(*BaseService).Start
	/home/user/go/pkg/mod/github.com/caffix/service@v0.0.0-20210101222658-354b1fdf7f24/base.go:50 +0x12c

```

**Comment by ZeroDot1** [comment]
Unfortunately, the problem occurred again today.
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xe7d9fe]

goroutine 3581 [running]:
github.com/yuin/gopher-lua.(*LState).PCall.func1(0x1a017c0, 0xc0003d5290, 0xc00895b9c0, 0x0, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2012 +0x11e
panic(0x1015700, 0x225a090)
	/usr/lib/go/src/runtime/panic.go:969 +0x1b9
github.com/yuin/gopher-lua.callGFunction(0xc0003d5290, 0x0, 0xc003d09100)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:262 +0x1f7
github.com/yuin/gopher-lua.init.3.func26(0xc0003d5290, 0xc07c240203, 0xc003d27000, 0x0)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:817 +0x39d
github.com/yuin/gopher-lua.mainLoop(0xc0003d5290, 0xc003d27000)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:31 +0xf4
github.com/yuin/gopher-lua.(*LState).callR(0xc0003d5290, 0x2, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1203 +0x256
github.com/yuin/gopher-lua.(*LState).Call(...)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1959
github.com/yuin/gopher-lua.(*LState).PCall(0xc0003d5290, 0x2, 0x0, 0x0, 0x1b07940, 0xc006b8b480)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2022 +0x114
github.com/yuin/gopher-lua.(*LState).CallByParam(0xc0003d5290, 0x1b20e40, 0xc003d0e800, 0x0, 0x1, 0x0, 0xc007891a78, 0x2, 0x2, 0x1b1e700, ...)
	/home/user/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2040 +0xe9
github.com/OWASP/Amass/v3/datasrcs.(*Script).dnsRequest(0xc0000c7680, 0x1b1e700, 0xc00ba2ea80, 0xc002f8bc20)
	/home/user/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.11.1/datasrcs/script.go:289 +0x35b
github.com/OWASP/Amass/v3/datasrcs.(*Script).OnRequest(0xc0000c7680, 0x1b1e700, 0xc00ba2ea80, 0x1032620, 0xc002f8bc20)
	/home/user/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.11.1/datasrcs/script.go:259 +0x113
reflect.Value.call(0xfd2f00, 0xc013801160, 0x13, 0x1175a1b, 0x4, 0xc00ba2f200, 0x2, 0x2, 0x9057f9329, 0x228a1c0, ...)
	/usr/lib/go/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0xfd2f00, 0xc013801160, 0x13, 0xc00ba2f200, 0x2, 0x2, 0x0, 0x1, 0xc000766ea0)
	/usr/lib/go/src/reflect/value.go:337 +0xb9
github.com/caffix/service.(*BaseService).processRequests.func1(0xf8c9a0, 0xc00ba2f230)
	/home/user/go/pkg/mod/github.com/caffix/service@v0.0.0-20210101222658-354b1fdf7f24/base.go:166 +0x1d5
github.com/caffix/queue.(*queue).Process(0xc00b6112f0, 0xc003828290)
	/home/user/go/pkg/mod/github.com/caffix/queue@v0.0.0-20210106184330-1d2e72b64fa0/queue.go:172 +0x4f
github.com/caffix/service.(*BaseService).processRequests(0xc0000c7680)
	/home/user/go/pkg/mod/github.com/caffix/service@v0.0.0-20210101222658-354b1fdf7f24/base.go:175 +0x92
created by github.com/caffix/service.(*BaseService).Start
	/home/user/go/pkg/mod/github.com/caffix/service@v0.0.0-20210101222658-354b1fdf7f24/base.go:50 +0x12c

```

**Comment by alfonsocaponi** [comment]
```
# uname -r && amass -version && go version
5.3.0-28-generic
v3.11.1
go version go1.15.7 linux/amd64
```

```
/snap/bin/amass enum -passive -max-dns-queries 10 -noresolvrate -nolocaldb -nocolor -d target.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xd944c0]

goroutine 3374 [running]:
github.com/OWASP/Amass/v3/resolvers.(*resolverPool).nextResolver(0xc00038a000, 0x1b16740, 0xc000128078, 0x0, 0xc014149ca8)
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/pool.go:98 +0xe0
github.com/OWASP/Amass/v3/resolvers.(*resolverPool).Query(0xc00038a000, 0x1b16740, 0xc000128078, 0xc00ebb2090, 0x3, 0x19f8e18, 0xc00f5e23f0, 0x0, 0x0)
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/pool.go:156 +0x125
github.com/OWASP/Amass/v3/resolvers.(*resolverPool).Query(0xc00008d260, 0x1b16740, 0xc000128078, 0xc00ebb2090, 0x3, 0x19f8e18, 0xc00f5d9560, 0x8, 0xc00f5d9560)
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/pool.go:196 +0x3e6
github.com/OWASP/Amass/v3/datasrcs.(*RADb).OnStart(0xc00f5d9560, 0x19f8f01, 0xc00f5d9560)
        /home/caffix/go/src/github.com/OWASP/Amass/datasrcs/radb.go:59 +0xb1
github.com/caffix/service.(*BaseService).Start(0xc00f5d9560, 0x0, 0x0)
        /home/caffix/go/pkg/mod/github.com/caffix/service@v0.0.0-20210101222658-354b1fdf7f24/base.go:52 +0x156
github.com/OWASP/Amass/v3/systems.(*LocalSystem).AddAndStart(0xc001db8360, 0x1b26000, 0xc00f5d9560, 0xc000f7fd40, 0x7dc28751e259d00)
        /home/caffix/go/src/github.com/OWASP/Amass/systems/local.go:115 +0x35
github.com/OWASP/Amass/v3/systems.(*LocalSystem).SetDataSources.func1(0x1b26000, 0xc00f5d9560, 0xc013846780)
        /home/caffix/go/src/github.com/OWASP/Amass/systems/local.go:133 +0x3e
created by github.com/OWASP/Amass/v3/systems.(*LocalSystem).SetDataSources
        /home/caffix/go/src/github.com/OWASP/Amass/systems/local.go:138 +0x105
```

**Comment by caffix** [comment]
@alfonsocaponi I am adding the checks to prevent this from happening. In the mean time, increase your `-max-dns-queries` to a minimum of one per resolver to avoid the problem
