### ISSUE TITLE
panic: reflect: slice index out of range

### ISSUE THREAD

**Issue by Viss** [OWASP/Amass#566]
I just tried a test run with the new build against google, and this is what happened:

cmdline: ./amass enum -src -ip -brute -active -ipv4 -nolocaldb -d google.com

```
panic: reflect: slice index out of range [recovered]
	panic: reflect: slice index out of range

goroutine 3484 [running]:
encoding/json.(*encodeState).marshal.func1(0xc01a43de20)
	/usr/local/go/src/encoding/json/encode.go:326 +0x85
panic(0xfa5ae0, 0x1aa41e0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
reflect.Value.Index(0xf90480, 0xc008101d60, 0x197, 0x4, 0x10c0100, 0xc020d180d8, 0x199)
	/usr/local/go/src/reflect/value.go:962 +0x1f2
encoding/json.arrayEncoder.encode(0xc01a1fdb90, 0xc0043a2000, 0xf90480, 0xc008101d60, 0x197, 0xfa0100)
	/usr/local/go/src/encoding/json/encode.go:886 +0x8d
encoding/json.sliceEncoder.encode(0xc01b09bf10, 0xc0043a2000, 0xf90480, 0xc008101d60, 0x197, 0x100)
	/usr/local/go/src/encoding/json/encode.go:860 +0x8f
encoding/json.structEncoder.encode(0xc0064b8d80, 0x5, 0x8, 0xc01a1fdbc0, 0xc0043a2000, 0x10cb900, 0xc008101d40, 0x199, 0xfe0100)
	/usr/local/go/src/encoding/json/encode.go:759 +0x2ab
encoding/json.ptrEncoder.encode(0xc01a1fdbf0, 0xc0043a2000, 0xffb400, 0xc008101d40, 0x16, 0xff0100)
	/usr/local/go/src/encoding/json/encode.go:915 +0x125
encoding/json.(*encodeState).reflectValue(0xc0043a2000, 0xffb400, 0xc008101d40, 0x16, 0xc01a430100)
	/usr/local/go/src/encoding/json/encode.go:358 +0x82
encoding/json.(*encodeState).marshal(0xc0043a2000, 0xffb400, 0xc008101d40, 0xc016100100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:330 +0xf4
encoding/json.(*Encoder).Encode(0xc01a43df40, 0xffb400, 0xc008101d40, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:206 +0x8b
main.saveJSONOutput(0xc01611e000, 0xc000154200, 0xc01610e300, 0xc012610560)
	/home/caffix/go/src/github.com/OWASP/Amass/cmd/amass/enum.go:492 +0x2f6
created by main.runEnumCommand
	/home/caffix/go/src/github.com/OWASP/Amass/cmd/amass/enum.go:212 +0x8d7
```

**Comment by caffix** [comment]
First time that has show up. Thank you for the information

**Comment by Viss** [comment]
I attempted a bunch of other domains and the error was exactly the same. I wasn't able to get it to run once.

If theres troubleshooting I can do to help, let me know!

**Comment by caffix** [comment]
@Viss Try removing `~/.config/amass` to see if a previous local graph database is causing the problem

**Comment by lucbarr** [comment]
Was a root cause found for this panic?

**Comment by caffix** [comment]
@lucbarr Changes made to the output stream that were later fixed. Have you experienced a similar issue recently?

**Comment by carlosotgz** [comment]
Hi. Unfortunately I'm facing this same issue constantly. It doesn't happen every single time but often enough to make Amass a bit unreliable. I noticed the comment above about removing the `~/.config/amass` folder but:
- I'm running Amass from the official Docker image and without persisting `~/.config/amass` (or actually any other directory)
- I'm running Amass enum passing the `-nolocaldb` flag. I'm not clear what the root cause of the issue is but, in case the case if was something related with a previous local graph database, shouldn't this flag remove this possibility?

For completeness, this is how I'm invoking Amass `enum -active -brute -p 80,443,8080 -d <domain> -src -ipv4 -nolocaldb -config /amass/config.ini -json amass-brute-active.jsonl` and this the error message I got:
```
panic: reflect: slice index out of range [recovered]
        panic: reflect: slice index out of range

goroutine 63 [running]:
encoding/json.(*encodeState).marshal.func1(0xc02210ce20)
        /usr/local/go/src/encoding/json/encode.go:328 +0x8d
panic(0xf83ee0, 0x1aac220)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
reflect.Value.Index(0xf70680, 0xc01111b7c0, 0x197, 0x1, 0x1090100, 0xc013069a70, 0x199)
        /usr/local/go/src/reflect/value.go:962 +0x1f2
encoding/json.arrayEncoder.encode(0xc00b0013b0, 0xc01e6c0100, 0xf70680, 0xc01111b7c0, 0x197, 0x100)
        /usr/local/go/src/encoding/json/encode.go:915 +0x8d
encoding/json.sliceEncoder.encode(0xc02031e290, 0xc01e6c0100, 0xf70680, 0xc01111b7c0, 0x197, 0x100)
        /usr/local/go/src/encoding/json/encode.go:888 +0xfe
encoding/json.structEncoder.encode(0xc00402db00, 0x5, 0x8, 0xc00b001410, 0xc01e6c0100, 0x10975c0, 0xc01111b7a0, 0x199, 0xfb0100)
        /usr/local/go/src/encoding/json/encode.go:761 +0x2ab
encoding/json.ptrEncoder.encode(0xc00b001440, 0xc01e6c0100, 0xfcc0e0, 0xc01111b7a0, 0x16, 0xfc0100)
        /usr/local/go/src/encoding/json/encode.go:944 +0x125
encoding/json.(*encodeState).reflectValue(0xc01e6c0100, 0xfcc0e0, 0xc01111b7a0, 0x16, 0xc022100100)
        /usr/local/go/src/encoding/json/encode.go:360 +0x82
encoding/json.(*encodeState).marshal(0xc01e6c0100, 0xfcc0e0, 0xc01111b7a0, 0xc0002e0100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:332 +0xf9
encoding/json.(*Encoder).Encode(0xc02210cf40, 0xfcc0e0, 0xc01111b7a0, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:206 +0x8b
main.saveJSONOutput(0xc002296680, 0xc0003de000, 0xc0002ef620, 0xc003c660f0)
        /go/src/github.com/OWASP/Amass/cmd/amass/enum.go:493 +0x312
created by main.runEnumCommand
        /go/src/github.com/OWASP/Amass/cmd/amass/enum.go:214 +0x9a9
```
I'm happy to help identifying where the issue is coming from, just need some pointers :)

**Comment by mplattner** [comment]
I have the same issue running this command:
`amass enum -active -brute -df amass-enum-domains.txt -ipv4 -v -o amass-enum-alldomains-nojson.txt -log amass-enum-alldomains-nojson.log`.

The file `amass-enum-domains.txt` contains 55 domains. amass seems to throw the error at different progress levels when running it multiple times. I thought its related to the `-json` parameter, but it also does throw the error without it.

I'm using the latest amass version 3.19.3.
I think this issue should be re-opened.

**Comment by vertazzar** [comment]
I swapped the json library with the jsontier package and im no longer getting any panics for months now. It's really strange

**Comment by mplattner** [comment]
Can you please give me some hints/instructions on how to swap the library? Thanks.

**Comment by 0xGodson** [comment]
any update here? I am using the latest version of amass

```sh
$ amass -version
v3.23.3
```

The command I used.

```sh
$ amass enum -active -df ../root-domain.txt -ipv4 -brute -w /opt/wordlists/SecLists/Discovery/DNS/deepmagic.com-prefixes-top500.txt -o amass-root-output-2.txt -config ~/configs/amass.ini
[...]
[...]
panic: reflect: slice index out of range [recovered]
	panic: reflect: slice index out of range

goroutine 337 [running]:
encoding/json.(*encodeState).marshal.func1()
	/opt/hostedtoolcache/go/1.19.10/x64/src/encoding/json/encode.go:327 +0x80
panic({0x10212cea0, 0x1022b68a0})
	/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/panic.go:884 +0x204
reflect.Value.Index({0x10211b7e0?, 0x1400414dfa0?, 0x14006f7c048?}, 0x0?)
	/opt/hostedtoolcache/go/1.19.10/x64/src/reflect/value.go:1412 +0x180
encoding/json.arrayEncoder.encode({0x14007625998?}, 0x140064a6000, {0x10211b7e0?, 0x1400414dfa0?, 0x102e50108?}, {0x80?, 0x0?})
	/opt/hostedtoolcache/go/1.19.10/x64/src/encoding/json/encode.go:915 +0x98
encoding/json.sliceEncoder.encode({0x14007625ae8?}, 0x140064a6000, {0x10211b7e0?, 0x1400414dfa0?, 0x140064a6000?}, {0xc?, 0x0?})
	/opt/hostedtoolcache/go/1.19.10/x64/src/encoding/json/encode.go:888 +0x298
encoding/json.structEncoder.encode({{{0x140039c3b00?, 0x100f4a180?, 0x14007625bf8?}, 0x1401b8aa480?}}, 0x140064a6000, {0x102240980?, 0x1400414df80?, 0x1400414df80?}, {0x8?, 0x5c?})
	/opt/hostedtoolcache/go/1.19.10/x64/src/encoding/json/encode.go:760 +0x178
encoding/json.ptrEncoder.encode({0x14007625d08?}, 0x140064a6000, {0x10218f2a0?, 0x1400414df80?, 0x14007625d18?}, {0xd4?, 0xc3?})
	/opt/hostedtoolcache/go/1.19.10/x64/src/encoding/json/encode.go:944 +0x1f4
encoding/json.(*encodeState).reflectValue(0x0?, {0x10218f2a0?, 0x1400414df80?, 0x100f45e58?}, {0x78?, 0x0?})
	/opt/hostedtoolcache/go/1.19.10/x64/src/encoding/json/encode.go:359 +0x70
encoding/json.(*encodeState).marshal(0x140002d4d80?, {0x10218f2a0?, 0x1400414df80?}, {0xc8?, 0x1d?})
	/opt/hostedtoolcache/go/1.19.10/x64/src/encoding/json/encode.go:331 +0x120
encoding/json.(*Encoder).Encode(0x14007625f38, {0x10218f2a0, 0x1400414df80})
	/opt/hostedtoolcache/go/1.19.10/x64/src/encoding/json/stream.go:206 +0x58
main.saveJSONOutput(0x0?, 0x140000a5b00, 0x0?, 0x0?)
	/home/runner/work/amass/amass/cmd/amass/enum.go:522 +0x250
created by main.runEnumCommand
	/home/runner/work/amass/amass/cmd/amass/enum.go:228 +0x99c
```
