### ISSUE TITLE
[BUG]: go get -v -u github.com/OWASP/Amass/v3/... does not work.

### ISSUE THREAD

**Issue by ZeroDot1** [OWASP/Amass#585]
```bash
[user@work ~]$ export GO111MODULE=on
[user@work ~]$ go get -v -u github.com/OWASP/Amass/v3/...
go get: github.com/knq/sysutil@v0.0.0-20191005231841-15668db23d08 updating to
	github.com/knq/sysutil@v1.0.0: parsing go.mod:
	module declares its path as: github.com/chromedp/sysutil
	        but was required as: github.com/knq/sysutil
[user@work ~]$ go get -v github.com/OWASP/Amass/cmd/amass
github.com/OWASP/Amass/cmd/amass imports
	github.com/OWASP/Amass/amass: cannot find module providing package github.com/OWASP/Amass/amass
github.com/OWASP/Amass/cmd/amass imports
	github.com/OWASP/Amass/amass/utils: cannot find module providing package github.com/OWASP/Amass/amass/utils
[user@work ~]$ 

```

**Comment by caffix** [comment]
The installation is not being performed correctly. Please see the documentation for installation instructions or join the Amass Discord server for additional help. In the future, these usage questions should be brought to our Discord server instead of creating issues. Thank you

**Comment by ZeroDot1** [comment]
I have configured everything correctly.

By the way, I can't use Discord because my internet is too slow and unstable. Sorry.

**Comment by caffix** [comment]
You cannot be using `go get -u` when obtaining the Amass project. Perhaps it would be better to see how the Amass Docker image is built as an example of how to correctly build the tool

**Comment by ZeroDot1** [comment]
On my side, everything is correct and freshly configured.
I think something is not working as it should.

```bash
[user@work ~]$ sudo docker build -t amass https://github.com/OWASP/Amass.git
[sudo] Passwort für user: 
Sending build context to Docker daemon  81.51MB
Step 1/12 : FROM golang:alpine as build
alpine: Pulling from library/golang
ba3557a56b15: Pull complete 
34a078c6c131: Pull complete 
e78f90fd1d94: Pull complete 
a2bd9309a95d: Pull complete 
643269e9b573: Pull complete 
Digest: sha256:1200cee7b13cbb50ba19633d435f8cdbe604f0874d1b0cda3b67a0f907c9968b
Status: Downloaded newer image for golang:alpine
 ---> ef4694cd3ff4
Step 2/12 : RUN apk --no-cache add git
 ---> Running in 01e814cf7178
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/6) Installing brotli-libs (1.0.9-r3)
(2/6) Installing nghttp2-libs (1.42.0-r1)
(3/6) Installing libcurl (7.74.0-r0)
(4/6) Installing expat (2.2.10-r1)
(5/6) Installing pcre2 (10.36-r0)
(6/6) Installing git (2.30.1-r0)
Executing busybox-1.32.1-r3.trigger
OK: 19 MiB in 21 packages
Removing intermediate container 01e814cf7178
 ---> 608648388752
Step 3/12 : RUN go get github.com/OWASP/Amass; exit 0
 ---> Running in 40b5b21daada
go: downloading github.com/OWASP/Amass v1.5.2
go: downloading github.com/OWASP/Amass v2.6.0+incompatible
Removing intermediate container 40b5b21daada
 ---> f089fd1d69b0
Step 4/12 : ENV GO111MODULE on
 ---> Running in 9d908b8d99be
Removing intermediate container 9d908b8d99be
 ---> c2a7d44feb95
Step 5/12 : WORKDIR /go/src/github.com/OWASP/Amass
 ---> Running in db7f0c2bf3d8
Removing intermediate container db7f0c2bf3d8
 ---> 7c45c6a8bc4d
Step 6/12 : RUN go install ./...
 ---> Running in b8b8729aa118
go: cannot find main module; see 'go help modules'
The command '/bin/sh -c go install ./...' returned a non-zero code: 1

```

**Comment by caffix** [comment]
@ZeroDot1 I think I see what's happening. The fixes are already in the `develop` branch, which is why my results were different from yours. Can you use a prebuilt binary between now and the next release?

**Comment by ZeroDot1** [comment]
Yes, I can use a prebuild until the next release.

**Comment by ZeroDot1** [comment]
While testing the prebuild version, an error occurred.

`$ '/go/bin/amass' enum -config '/config.ini' -passive -d armornetwork.org`

```go
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xe6d4de]

goroutine 32 [running]:
github.com/yuin/gopher-lua.(*LState).PCall.func1(0x19c7f90, 0xc0004b11e0, 0xc008ce19b0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2012 +0x11e
panic(0x1002620, 0x220fc30)
	/opt/hostedtoolcache/go/1.15.8/x64/src/runtime/panic.go:969 +0x1b9
github.com/yuin/gopher-lua.callGFunction(0xc0004b11e0, 0x0, 0xc000c17300)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:262 +0x1f7
github.com/yuin/gopher-lua.init.3.func26(0xc0004b11e0, 0xc07c080603, 0xc001530000, 0x0)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:817 +0x39d
github.com/yuin/gopher-lua.mainLoopWithContext(0xc0004b11e0, 0xc001530000)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:60 +0x126
github.com/yuin/gopher-lua.(*LState).callR(0xc0004b11e0, 0x2, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1203 +0x256
github.com/yuin/gopher-lua.(*LState).Call(...)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1959
github.com/yuin/gopher-lua.(*LState).PCall(0xc0004b11e0, 0x2, 0x0, 0x0, 0x1acc720, 0xc002f57480)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2022 +0x114
github.com/yuin/gopher-lua.(*LState).CallByParam(0xc0004b11e0, 0x1ae5180, 0xc00309a2c0, 0x0, 0x1, 0x0, 0xc00316da68, 0x2, 0x2, 0x1ae2b80, ...)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2040 +0xe9
github.com/OWASP/Amass/v3/datasrcs.(*Script).dnsRequest(0xc0000a6140, 0x1ae2b80, 0xc010755a70, 0xc000c12d80)
	/home/runner/work/Amass/Amass/datasrcs/script.go:294 +0x35b
github.com/OWASP/Amass/v3/datasrcs.(*Script).OnRequest(0xc0000a6140, 0x1ae2b80, 0xc010755a70, 0x101ef80, 0xc000c12d80)
	/home/runner/work/Amass/Amass/datasrcs/script.go:264 +0x113
reflect.Value.call(0xfc1280, 0xc00bd00c60, 0x13, 0x115f4a2, 0x4, 0xc00a0ce270, 0x2, 0x2, 0xc000c07080, 0xc00322c000, ...)
	/opt/hostedtoolcache/go/1.15.8/x64/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0xfc1280, 0xc00bd00c60, 0x13, 0xc00a0ce270, 0x2, 0x2, 0x0, 0x0, 0x1)
	/opt/hostedtoolcache/go/1.15.8/x64/src/reflect/value.go:337 +0xb9
github.com/caffix/service.(*BaseService).processRequests.func1(0xf7c0c0, 0xc00a0ce2a0)
	/home/runner/go/pkg/mod/github.com/caffix/service@v0.0.0-20210202222504-bfa33e78ab27/base.go:171 +0x1e5
github.com/caffix/queue.(*queue).Process(0xc010e56210, 0xc00b73a160)
	/home/runner/go/pkg/mod/github.com/caffix/queue@v0.0.0-20210106184330-1d2e72b64fa0/queue.go:172 +0x4f
github.com/caffix/service.(*BaseService).processRequests(0xc0000a6140)
	/home/runner/go/pkg/mod/github.com/caffix/service@v0.0.0-20210202222504-bfa33e78ab27/base.go:180 +0xb8
created by github.com/caffix/service.(*BaseService).Start
	/home/runner/go/pkg/mod/github.com/caffix/service@v0.0.0-20210202222504-bfa33e78ab27/base.go:50 +0x12c

```

**Comment by ZeroDot1** [comment]
Hi @caffix,

Unfortunately, while trying to update, I just noticed that the problem still exists.

```go
$ export GO111MODULE=on
[user@work ~]$ go get -v -u github.com/OWASP/Amass/v3/...
go: downloading github.com/OWASP/Amass v1.5.2
go: downloading github.com/OWASP/Amass/v3 v3.11.6
go: downloading github.com/OWASP/Amass v2.6.0+incompatible
go: downloading github.com/rakyll/statik v0.1.7
go: downloading github.com/fatih/color v1.10.0
go: downloading github.com/caffix/eventbus v0.0.0-20210301213705-9ab42753d12d
go: downloading github.com/caffix/pipeline v0.0.0-20210301171240-503915daec5b
go: downloading github.com/caffix/queue v0.0.0-20210301212750-6e488abe1004
go: downloading github.com/caffix/service v0.0.0-20210202222504-bfa33e78ab27
go: downloading github.com/caffix/stringset v0.0.0-20201218054545-37e95a70826c
go: downloading github.com/miekg/dns v1.1.35
go: downloading golang.org/x/net v0.0.0-20201224014010-6772e930b67b
go: downloading github.com/go-ini/ini v1.62.0
go: downloading github.com/google/uuid v1.1.3
go: downloading github.com/yl2chen/cidranger v1.0.2
go: downloading github.com/miekg/dns v1.1.40
go: downloading github.com/PuerkitoBio/goquery v1.6.0
go: downloading github.com/geziyor/geziyor v0.0.0-20191212210344-cfb16fe1ee0e
go: downloading golang.org/x/net v0.0.0-20210226172049-e18ecbb05110
go: downloading github.com/cjoudrey/gluaurl v0.0.0-20161028222611-31cbb9bef199
go: downloading github.com/google/uuid v1.2.0
go: downloading github.com/cloudflare/cloudflare-go v0.13.6
go: downloading github.com/dghubble/go-twitter v0.0.0-20201011215211-4b180d0cc78d
go: downloading github.com/yuin/gopher-lua v0.0.0-20200816102855-ee81675732da
go: downloading github.com/PuerkitoBio/goquery v1.6.1
go: downloading github.com/geziyor/geziyor v0.0.0-20210128175025-129402d754a6
go: downloading golang.org/x/oauth2 v0.0.0-20201208152858-08078c50e5b5
go: downloading layeh.com/gopher-json v0.0.0-20201124131017-552bb3c4c3bf
go: downloading github.com/AndreasBriese/bbloom v0.0.0-20190825152654-46b345b51c96
go: downloading github.com/cayleygraph/cayley v0.7.7
go: downloading github.com/cloudflare/cloudflare-go v0.13.8
go: downloading golang.org/x/oauth2 v0.0.0-20210220000619-9bb904979d93
go: downloading github.com/cayleygraph/quad v1.2.4
go: downloading go.uber.org/ratelimit v0.1.0
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/hashicorp/go-multierror v1.1.0
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading golang.org/x/sys v0.0.0-20201119102817-f84b799fce68
go: downloading github.com/chromedp/cdproto v0.0.0-20191114225735-6626966fbae4
go: downloading github.com/chromedp/chromedp v0.5.2-0.20191114231622-97580065bae3
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/andybalholm/cascadia v1.1.0
go: downloading golang.org/x/sys v0.0.0-20210301091718-77cc2087c03b
go: downloading github.com/andybalholm/cascadia v1.2.0
go: downloading github.com/chromedp/chromedp v0.6.6
go: downloading github.com/cenkalti/backoff v2.1.1+incompatible
go: downloading github.com/dghubble/sling v1.3.0
go: downloading github.com/chromedp/cdproto v0.0.0-20210227213635-aabfe75e3e09
go: downloading golang.org/x/text v0.3.5
go: downloading github.com/cenkalti/backoff v1.1.0
go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
go: downloading github.com/hidal-go/hidalgo v0.0.0-20190814174001-42e03f3b5eaa
go: downloading github.com/cenkalti/backoff v2.2.1+incompatible
go: downloading github.com/go-sql-driver/mysql v1.4.1
go: downloading github.com/gobuffalo/packr/v2 v2.7.1
go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
go: downloading github.com/hashicorp/errwrap v1.1.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/gobuffalo/packr v1.30.1
go: downloading github.com/hidal-go/hidalgo v0.0.0-20201109092204-05749a6d73df
go: downloading github.com/gobuffalo/packr/v2 v2.8.1
go: downloading github.com/go-kit/kit v0.8.0
go: downloading github.com/prometheus/client_golang v1.0.0
go: downloading github.com/go-kit/kit v0.10.0
go: downloading github.com/prometheus/client_golang v1.9.0
go: downloading github.com/temoto/robotstxt v1.1.1
go: downloading github.com/gobwas/ws v1.0.2
go: downloading github.com/mailru/easyjson v0.7.0
go: downloading github.com/google/go-querystring v1.0.0
go: downloading github.com/gobwas/ws v1.0.4
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading google.golang.org/appengine v1.6.6
go: downloading github.com/tylertreat/BoomFilters v0.0.0-20181028192813-611b3dbe80e8
go: downloading github.com/boltdb/bolt v1.3.1
go: downloading google.golang.org/appengine v1.6.7
go: downloading github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4
go: downloading github.com/prometheus/common v0.4.1
go: downloading github.com/beorn7/perks v1.0.0
go: downloading github.com/tylertreat/BoomFilters v0.0.0-20200520150052-42a7b4300c0c
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/prometheus/procfs v0.0.2
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/prometheus/common v0.18.0
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/prometheus/procfs v0.6.0
go: downloading github.com/knq/sysutil v0.0.0-20191005231841-15668db23d08
go: downloading github.com/gobwas/pool v0.2.0
go: downloading github.com/gobwas/httphead v0.0.0-20180130184737-2c6c146eadee
go: downloading github.com/gogo/protobuf v1.3.0
go: downloading github.com/gobwas/pool v0.2.1
go: downloading github.com/dennwc/base v1.0.0
go: downloading github.com/gobuffalo/envy v1.7.1
go: downloading github.com/knq/sysutil v1.0.0
go: downloading github.com/gobuffalo/logger v1.0.1
go: downloading github.com/gobwas/httphead v0.1.0
go: downloading github.com/gobuffalo/envy v1.9.0
go: downloading github.com/gobuffalo/logger v1.0.3
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/spf13/cobra v0.0.5
go: downloading github.com/VividCortex/gohistogram v1.0.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/spf13/cobra v1.1.3
go: downloading google.golang.org/protobuf v1.25.0
go: downloading github.com/gobuffalo/packd v0.3.0
go: downloading github.com/gobuffalo/packd v1.0.0
go: downloading golang.org/x/tools v0.0.0-20200825202427-b303f430e36d
go: downloading github.com/joho/godotenv v1.3.0
go: downloading github.com/rogpeppe/go-internal v1.5.0
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading golang.org/x/tools v0.1.0
go: downloading github.com/sirupsen/logrus v1.8.0
go: downloading github.com/rogpeppe/go-internal v1.7.0
go: downloading golang.org/x/sync v0.0.0-20201207232520-09787c993a3a
go: downloading golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.2
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.3
go get: github.com/knq/sysutil@v0.0.0-20191005231841-15668db23d08 updating to
	github.com/knq/sysutil@v1.0.0: parsing go.mod:
	module declares its path as: github.com/chromedp/sysutil
	        but was required as: github.com/knq/sysutil

```

**Comment by caffix** [comment]
@ZeroDot1 You're still using the `-u` flag, which can cause dependencies to be upgraded before we have tested them

**Comment by ZeroDot1** [comment]
Problem solved, thanks for your support.
