### ISSUE TITLE
null pointer exception

### ISSUE THREAD

**Issue by fxa** [OWASP/Amass#589]
amass enum -passive -d dm.deamass enum -passive -d dm.de
ended up with:

```shel
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xe73b9e]

goroutine 6210 [running]:
github.com/yuin/gopher-lua.(*LState).PCall.func1(0x19cf310, 0xc0000ba790, 0xc009c159b0, 0x0, 0x0, 0x0)
	/build/amass-dqmTjA/amass-3.11.5/build/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2012 +0x11e
panic(0x10090e0, 0x221df30)
	/usr/lib/go-1.15/src/runtime/panic.go:969 +0x1b9
github.com/yuin/gopher-lua.callGFunction(0xc0000ba790, 0x0, 0xc0067e5180)
	/build/amass-dqmTjA/amass-3.11.5/build/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:262 +0x1f7
github.com/yuin/gopher-lua.init.3.func26(0xc0000ba790, 0xc07c1c0203, 0xc0069ae000, 0x0)
	/build/amass-dqmTjA/amass-3.11.5/build/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:817 +0x39d
github.com/yuin/gopher-lua.mainLoopWithContext(0xc0000ba790, 0xc0069ae000)
	/build/amass-dqmTjA/amass-3.11.5/build/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:60 +0x126
github.com/yuin/gopher-lua.(*LState).callR(0xc0000ba790, 0x2, 0x0, 0x0)
	/build/amass-dqmTjA/amass-3.11.5/build/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1203 +0x256
github.com/yuin/gopher-lua.(*LState).Call(...)
	/build/amass-dqmTjA/amass-3.11.5/build/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1959
github.com/yuin/gopher-lua.(*LState).PCall(0xc0000ba790, 0x2, 0x0, 0x0, 0x1ad4260, 0xc004600e40)
	/build/amass-dqmTjA/amass-3.11.5/build/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2022 +0x114
github.com/yuin/gopher-lua.(*LState).CallByParam(0xc0000ba790, 0x1aed080, 0xc006828040, 0x0, 0x1, 0x0, 0xc00370ea68, 0x2, 0x2, 0x1aeaa80, ...)
	/build/amass-dqmTjA/amass-3.11.5/build/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2040 +0xe9
github.com/OWASP/Amass/v3/datasrcs.(*Script).dnsRequest(0xc00130f7c0, 0x1aeaa80, 0xc009582c90, 0xc00958a480)
	/build/amass-dqmTjA/amass-3.11.5/datasrcs/script.go:294 +0x35b
github.com/OWASP/Amass/v3/datasrcs.(*Script).OnRequest(0xc00130f7c0, 0x1aeaa80, 0xc009582c90, 0x1025b40, 0xc00958a480)
	/build/amass-dqmTjA/amass-3.11.5/datasrcs/script.go:264 +0x113
reflect.Value.call(0xfc7d40, 0xc009575ee0, 0x13, 0x1166762, 0x4, 0xc009583200, 0x2, 0x2, 0xc0095883c0, 0xc0080fd980, ...)
	/usr/lib/go-1.15/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0xfc7d40, 0xc009575ee0, 0x13, 0xc009583200, 0x2, 0x2, 0x791855, 0x0, 0x1)
	/usr/lib/go-1.15/src/reflect/value.go:337 +0xb9
github.com/caffix/service.(*BaseService).processRequests.func1(0xf82460, 0xc009583230)
	/build/amass-dqmTjA/amass-3.11.5/build/pkg/mod/github.com/caffix/service@v0.0.0-20210202222504-bfa33e78ab27/base.go:171 +0x1e5
github.com/caffix/queue.(*queue).Process(0xc0067a7ad0, 0xc007b80d20)
	/build/amass-dqmTjA/amass-3.11.5/build/pkg/mod/github.com/caffix/queue@v0.0.0-20210106184330-1d2e72b64fa0/queue.go:172 +0x4f
github.com/caffix/service.(*BaseService).processRequests(0xc00130f7c0)
	/build/amass-dqmTjA/amass-3.11.5/build/pkg/mod/github.com/caffix/service@v0.0.0-20210202222504-bfa33e78ab27/base.go:180 +0xb8
created by github.com/caffix/service.(*BaseService).Start
	/build/amass-dqmTjA/amass-3.11.5/build/pkg/mod/github.com/caffix/service@v0.0.0-20210202222504-bfa33e78ab27/base.go:50 +0x12c
```
did only occur once. I just wanted to inform you

**Comment by fxa** [comment]
Perhaps related with [https://github.com/OWASP/Amass/issues/519] ?

**Comment by caffix** [comment]
This is also an older version of Amass

**Comment by fxa** [comment]
yes, I know. The current version is 3.11.8 and this is 3.11.5
But according to my experiences null pointer errors don't just disappear, if you are not explicitly search for them.
It could be, that is an error in an error handling routine. When the error occurred, my internet connection broke down. So  perhaps the error could be in the error handling of handling the results of an online call. That could be the reason, why the error occurs only very seldom

**Comment by caffix** [comment]
That portion of the code has been updated since the version you're running, so your feedback will be more useful when you're up-to-date

**Comment by fxa** [comment]
ah, fine to know! So we can close this issue
