### ISSUE TITLE
panic: interface conversion: interface {} is string, not time.Time

### ISSUE THREAD

**Issue by cyb3rsalih** [OWASP/Amass#615]
I am getting the error when using `amass track -d example.com`

System:  `Ubuntu 20.04.2 LTS`
Go version: `1.16.3 linux/amd64`
Amass version: `v3.12.2`

```
panic: interface conversion: interface {} is string, not time.Time
goroutine 1 [running]:
github.com/caffix/netmap.(*Graph).EventDateRange(0xc000020120, 0xc005121800, 0x2                   4, 0xc008455c38, 0x1, 0x0, 0xc008355000, 0x7fffee506739, 0xc00775deb0)
        /root/go/pkg/mod/github.com/caffix/netmap@v0.0.0-20210412003155-5aec1390                   9475/event.go:212 +0x2f8
main.orderedEvents(0xc00775deb0, 0x1, 0x1, 0xc000020120, 0xc00775deb0, 0x1, 0x1,                    0x8, 0x203000, 0x203000, ...)
        /root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.12.2/cmd/amass/main.                   go:274 +0x1a5
main.runTrackCommand(0xc00003c0a0, 0x2, 0x2)
        /root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.12.2/cmd/amass/track                   .go:159 +0xb29
main.main()
        /root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.12.2/cmd/amass/main.                   go:127 +0x55f
```

**Comment by caffix** [comment]
Thank you for the helpful feedback!

**Comment by caffix** [comment]
@cyb3rsalih Export data of interest from the Amass graph database and then remove the current db.

`rm -rf ~/.config/amass`

The DNS names saved can be provided to the next enumeration using the `-nf` flag

**Comment by kerberosmansour** [comment]
Sam issue elsewhere:

System: MacOs 11.5
Amass version: v3.13.4

AmassFilter % amass db -show -ip -df NewTLDs.txt
panic: interface conversion: interface {} is string, not time.Time

goroutine 1 [running]:
github.com/caffix/netmap.(*Graph).EventDateRange(0xc0028d4060, 0xc00c732ff0, 0x24, 0xc00ae98ca0, 0x1b7ce00, 0x9, 0x9, 0x10, 0x10)
	/home/runner/go/pkg/mod/github.com/caffix/netmap@v0.0.0-20210715165045-3ed7a4527a3d/event.go:212 +0x2f8
main.orderedEvents.func1(0x6, 0x0, 0x1b9a780)
	/home/runner/work/Amass/Amass/cmd/amass/main.go:263 +0x79
sort.quickSort_func(0xc00c8a3d78, 0xc00ae98ca0, 0x0, 0x9, 0x8)
	/opt/hostedtoolcache/go/1.16.5/x64/src/sort/zfuncversion.go:154 +0x1b8
sort.Slice(0x1b6e160, 0xc00912c510, 0xc00c8a3d78)
	/opt/hostedtoolcache/go/1.16.5/x64/src/sort/slice.go:20 +0xe8
main.orderedEvents(0xc0004c0b00, 0x9, 0x10, 0xc0028d4060, 0xc0028d4060, 0x0, 0x0, 0x9900000000000000, 0xc00036de20, 0x99ea1dd306ef315e, ...)
	/home/runner/work/Amass/Amass/cmd/amass/main.go:260 +0xef
main.runDBCommand(0xc000194140, 0x4, 0x4)
	/home/runner/work/Amass/Amass/cmd/amass/db.go:166 +0xdeb
main.main()
	/home/runner/work/Amass/Amass/cmd/amass/main.go:119 +0x431
