### ISSUE TITLE
Enum crash

### ISSUE THREAD

**Issue by 0xceba** [OWASP/Amass#689]
I am attempting to use Amass enum on a fresh linode node but it's crashing after enumerating a handful of results-

```
uname -a
Linux localhost 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

amass --version
v3.13.4

amass enum -active -brute -w XXX -d XXX.XXX,XXX.XXX -o XXX
...
goroutine 723909 [select]:
github.com/caffix/resolve.(*baseResolver).queueQuery(0xc002bdeaa0, 0x1adb990, 0xc030c4db40, 0xc00bb2b7a0, 0x0, 0xc003a25c01)
        /home/admin/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210713232312-b68cd71e4a53/base.go:213 +0x355
github.com/caffix/resolve.(*baseResolver).Query(0xc002bdeaa0, 0x1adb990, 0xc030c4db40, 0xc00bb2b7a0, 0x0, 0x0, 0x0, 0x1ac5440, 0xc01873cdf8)
        /home/admin/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210713232312-b68cd71e4a53/base.go:166 +0x14e
github.com/caffix/resolve.(*resolverPool).Query(0xc002ed8090, 0x1adb990, 0xc030c4db40, 0xc00bb2b7a0, 0x0, 0xc04a0533f0, 0xc00bae5050, 0x1ac5440, 0xc024041458)
        /home/admin/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210713232312-b68cd71e4a53/pool.go:212 +0x1cc
github.com/OWASP/Amass/v3/enum.(*dNSTask).processDNSRequest(0xc002558610, 0x1adb990, 0xc030c4db40, 0xc03454f5c0, 0x1ac5420, 0xc034b1a268, 0x8, 0xfeb420, 0x201, 0xc034b1a268)
        /home/admin/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.13.4/enum/dns.go:143 +0x1fe
github.com/OWASP/Amass/v3/enum.(*dNSTask).Process(0xc002558610, 0x1adb990, 0xc030c4db40, 0x1ad24a8, 0xc03454f5c0, 0x1ac5420, 0xc034b1a268, 0x1ad2400, 0xc0348ffc80, 0x0, ...)
        /home/admin/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.13.4/enum/dns.go:118 +0xd2
github.com/caffix/pipeline.(*dynamicPool).executeTask.func1(0xc030be5e90, 0x1adb990, 0xc030c4db40, 0x1ae11c0, 0xc002dc0b90, 0x1ad24a8, 0xc03454f5c0)
        /home/admin/go/pkg/mod/github.com/caffix/pipeline@v0.0.0-20210522041607-d06330c4484a/pool.go:110 +0x122
created by github.com/caffix/pipeline.(*dynamicPool).executeTask
        /home/admin/go/pkg/mod/github.com/caffix/pipeline@v0.0.0-20210522041607-d06330c4484a/pool.go:107 +0x146

goroutine 713046 [semacquire]:
sync.runtime_SemacquireMutex(0xc002ec7df4, 0x4dce00, 0x1)
        /home/admin/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc002ec7df0)
        /home/admin/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /home/admin/go/src/sync/mutex.go:81
github.com/caffix/resolve.(*slidingWindowTimeouts).updateTimeouts(0xc002ec7df0, 0xc00a39c100, 0xf, 0xc049e82000, 0x0)
        /home/admin/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210713232312-b68cd71e4a53/state.go:188 +0x6d6
github.com/caffix/resolve.(*resolverPool).Query(0xc002ed8090, 0x1adb990, 0xc030c4db40, 0xc049e82000, 0x0, 0xc025865680, 0xc049e403f0, 0x1ac5440, 0xc039f89fe0)
        /home/admin/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210713232312-b68cd71e4a53/pool.go:224 +0x292
github.com/OWASP/Amass/v3/enum.(*dNSTask).processDNSRequest(0xc002558610, 0x1adb990, 0xc030c4db40, 0xc04e6808a0, 0x1ac5420, 0xc056031a88, 0x8, 0xfeb420, 0x1, 0xc056031a88)
        /home/admin/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.13.4/enum/dns.go:143 +0x1fe
github.com/OWASP/Amass/v3/enum.(*dNSTask).Process(0xc002558610, 0x1adb990, 0xc030c4db40, 0x1ad24a8, 0xc04e6808a0, 0x1ac5420, 0xc056031a88, 0x0, 0xc048fe3710, 0x40fd78, ...)
        /home/admin/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.13.4/enum/dns.go:118 +0xd2
github.com/caffix/pipeline.(*dynamicPool).executeTask.func1(0xc030be5e90, 0x1adb990, 0xc030c4db40, 0x1ae11c0, 0xc002dc0b90, 0x1ad24a8, 0xc04e6808a0)
        /home/admin/go/pkg/mod/github.com/caffix/pipeline@v0.0.0-20210522041607-d06330c4484a/pool.go:110 +0x122
created by github.com/caffix/pipeline.(*dynamicPool).executeTask
        /home/admin/go/pkg/mod/github.com/caffix/pipeline@v0.0.0-20210522041607-d06330c4484a/pool.go:107 +0x146

goroutine 721601 [semacquire]:
sync.runtime_SemacquireMutex(0xc002ec7df4, 0x4dce00, 0x1)
        /home/admin/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc002ec7df0)
        /home/admin/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /home/admin/go/src/sync/mutex.go:81
github.com/caffix/resolve.(*slidingWindowTimeouts).updateTimeouts(0xc002ec7df0, 0xc00a39dde0, 0xf, 0xc03b0c1200, 0x0)
        /home/admin/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210713232312-b68cd71e4a53/state.go:188 +0x6d6
github.com/caffix/resolve.(*resolverPool).Query(0xc002ed8090, 0x1adb990, 0xc030c4db40, 0xc03b0c1200, 0x0, 0xc0366d5860, 0xc036117710, 0x1ac5440, 0xc0324cb908)
        /home/admin/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210713232312-b68cd71e4a53/pool.go:224 +0x292
github.com/OWASP/Amass/v3/enum.(*dNSTask).processDNSRequest(0xc002558610, 0x1adb990, 0xc030c4db40, 0xc047399e60, 0x1ac5420, 0xc025cd4ad8, 0x8, 0xfeb420, 0x1, 0xc025cd4ad8)
        /home/admin/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.13.4/enum/dns.go:143 +0x1fe
github.com/OWASP/Amass/v3/enum.(*dNSTask).Process(0xc002558610, 0x1adb990, 0xc030c4db40, 0x1ad24a8, 0xc047399e60, 0x1ac5420, 0xc025cd4ad8, 0x464080, 0xc00dbe2a20, 0xc01c882f20, ...)
        /home/admin/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.13.4/enum/dns.go:118 +0xd2
github.com/caffix/pipeline.(*dynamicPool).executeTask.func1(0xc030be5e90, 0x1adb990, 0xc030c4db40, 0x1ae11c0, 0xc002dc0b90, 0x1ad24a8, 0xc047399e60)
        /home/admin/go/pkg/mod/github.com/caffix/pipeline@v0.0.0-20210522041607-d06330c4484a/pool.go:110 +0x122
created by github.com/caffix/pipeline.(*dynamicPool).executeTask
        /home/admin/go/pkg/mod/github.com/caffix/pipeline@v0.0.0-20210522041607-d06330c4484a/pool.go:107 +0x146

goroutine 726345 [semacquire]:
sync.runtime_SemacquireMutex(0xc002ec7df4, 0x4dce00, 0x1)
        /home/admin/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc002ec7df0)
        /home/admin/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /home/admin/go/src/sync/mutex.go:81
github.com/caffix/resolve.(*slidingWindowTimeouts).updateTimeouts(0xc002ec7df0, 0xc00a39cc90, 0x10, 0xc034871100, 0x0)
        /home/admin/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210713232312-b68cd71e4a53/state.go:188 +0x6d6
github.com/caffix/resolve.(*resolverPool).Query(0xc002ed8090, 0x1adb990, 0xc030c4db40, 0xc034871170, 0x0, 0xc0348f0f60, 0xc019a79ef0, 0x1ac5440, 0xc00ba2d9c8)
        /home/admin/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210713232312-b68cd71e4a53/pool.go:224 +0x292
github.com/OWASP/Amass/v3/enum.(*dNSTask).processDNSRequest(0xc002558610, 0x1adb990, 0xc030c4db40, 0xc0113c30e0, 0x1ac5420, 0xc0429e9180, 0x8, 0xfeb420, 0x101, 0xc0429e9180)
        /home/admin/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.13.4/enum/dns.go:143 +0x1fe
github.com/OWASP/Amass/v3/enum.(*dNSTask).Process(0xc002558610, 0x1adb990, 0xc030c4db40, 0x1ad24a8, 0xc0113c30e0, 0x1ac5420, 0xc0429e9180, 0x1ad2400, 0xc01b5a71a0, 0x0, ...)
        /home/admin/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.13.4/enum/dns.go:118 +0xd2
github.com/caffix/pipeline.(*dynamicPool).executeTask.func1(0xc030be5e90, 0x1adb990, 0xc030c4db40, 0x1ae11c0, 0xc002dc0b90, 0x1ad24a8, 0xc0113c30e0)
        /home/admin/go/pkg/mod/github.com/caffix/pipeline@v0.0.0-20210522041607-d06330c4484a/pool.go:110 +0x122
created by github.com/caffix/pipeline.(*dynamicPool).executeTask
        /home/admin/go/pkg/mod/github.com/caffix/pipeline@v0.0.0-20210522041607-d06330c4484a/pool.go:107 +0x146
```

**Comment by 0xceba** [comment]
The problem has not been resolved but I have closed it after seeing "🛑 Please avoid opening GitHub issues for support requests or questions!" in README.md. I will seek assistance in the Discord server.
