### ISSUE TITLE
error showing 

### ISSUE THREAD

**Issue by khanjanny** [OWASP/Amass#706]
```
panic: runtime error: integer divide by zero

goroutine 477048 [running]:
github.com/caffix/resolve.(*resolverPool).nextResolver(0xc0020f3830, 0x1bbb248, 0xc00003e098, 0x0, 0x450cc5)
        /home/khan/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210920205119-7c35ff3e3771/pool.go:125 +0x439
github.com/caffix/resolve.(*resolverPool).Query(0xc0020f3830, 0x1bbb248, 0xc00003e098, 0xc00003c990, 0x3, 0x1a8c7d8, 0xc0020f2480, 0x8, 0xc0020f2480)
        /home/khan/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210920205119-7c35ff3e3771/pool.go:207 +0x165
github.com/OWASP/Amass/v3/datasrcs.(*RADb).OnStart(0xc0020f2480, 0x1a8c701, 0xc0020f2480)
        /home/khan/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/datasrcs/radb.go:59 +0xb1
github.com/caffix/service.(*BaseService).Start(0xc0020f2480, 0x0, 0x0)
        /home/khan/go/pkg/mod/github.com/caffix/service@v0.0.0-20210920205156-38bde8eb0503/base.go:52 +0x156
github.com/OWASP/Amass/v3/systems.(*LocalSystem).AddAndStart(0xc002800ea0, 0x1bc9d70, 0xc0020f2480, 0x8b0e7f81e4715042, 0xf67a6934da1a780d)
        /home/khan/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/systems/local.go:108 +0x35
github.com/OWASP/Amass/v3/systems.(*LocalSystem).SetDataSources.func1(0x1bc9d70, 0xc0020f2480, 0xc00dd193e0)
        /home/khan/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/systems/local.go:126 +0x3e
created by github.com/OWASP/Amass/v3/systems.(*LocalSystem).SetDataSources
        /home/khan/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/systems/local.go:131 +0x105

```

after running sometimes it shows this type of error ..am running on Windows WSL

**Comment by caffix** [comment]
We do not currently support Windows WSL
