### ISSUE TITLE
amass net -cidr and amass net -asn error

### ISSUE THREAD

**Issue by lacroutelacroute** [OWASP/Amass#72]
hello admin

use snapd amass
snap install --edge amass

when I run these 2 commands I encounter a strange error here

:~$ amass net -addr 202.160.32.0-255
No root domain names were provided

:~$ amass net -asn 13374,14618
No root domain names were provided

:~$ amass net -cidr 192.184.113.0/24,104.154.0.0/15
No root domain names were provided

my dns resolution works

**Comment by fork-while-fork** [comment]
Due to it's loud and intrusive nature, that functionality (search via networks and ASNs) has been moved outside of the normal amass workflow and into the amass.netdomains tool. You can find information on that tool in the readme (https://github.com/OWASP/Amass#amassnetdomains).

**Comment by lacroutelacroute** [comment]
crash 
amass.netdomains  --addr 202.160.16.31.0-255

:~$ amass.netdomains  --addr 202.160.16.31.0-255
unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffffffffffff pc=0x78ad8e]

goroutine 1 [running]:
runtime.throw(0x84e78a, 0x5)
	/go/src/github.com/OWASP/Amass/parts/go/build/src/runtime/panic.go:608 +0x72 fp=0xc000052768 sp=0xc000052738 pc=0x42c072
runtime.sigpanic()
	/go/src/github.com/OWASP/Amass/parts/go/build/src/runtime/signal_unix.go:397 +0x275 fp=0xc0000527b8 sp=0xc000052768 pc=0x440b25
main.(*parseIPs).parseRange(0xc000468060, 0x7ffca1e8a1b3, 0x13, 0x1, 0xc0000d4010)
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/cmd/amass.netdomains/parsing.go:124 +0x2fe fp=0xc000052898 sp=0xc0000527b8 pc=0x78ad8e
main.(*parseIPs).Set(0xc000468060, 0x7ffca1e8a1b3, 0x13, 0x0, 0x0)
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/cmd/amass.netdomains/parsing.go:91 +0xc8 fp=0xc000052948 sp=0xc000052898 pc=0x78a6d8
flag.(*FlagSet).parseOne(0xc000070180, 0x1e, 0xc000024111, 0xc000052ba0)
	/go/src/github.com/OWASP/Amass/parts/go/build/src/flag/flag.go:906 +0x37b fp=0xc000052b40 sp=0xc000052948 pc=0x4d358b
flag.(*FlagSet).Parse(0xc000070180, 0xc00001e0a0, 0x2, 0x2, 0x860e42, 0x28)
	/go/src/github.com/OWASP/Amass/parts/go/build/src/flag/flag.go:925 +0x62 fp=0xc000052b70 sp=0xc000052b40 pc=0x4d3e42
flag.Parse()
	/go/src/github.com/OWASP/Amass/parts/go/build/src/flag/flag.go:953 +0x6f fp=0xc000052bb0 sp=0xc000052b70 pc=0x4d3f6f
main.main()
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/cmd/amass.netdomains/main.go:41 +0x2e6 fp=0xc000052f98 sp=0xc000052bb0 pc=0x788cf6
runtime.main()
	/go/src/github.com/OWASP/Amass/parts/go/build/src/runtime/proc.go:201 +0x207 fp=0xc000052fe0 sp=0xc000052f98 pc=0x42d9e7
runtime.goexit()
	/go/src/github.com/OWASP/Amass/parts/go/build/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000052fe8 sp=0xc000052fe0 pc=0x4583e1

goroutine 9 [select]:
github.com/OWASP/Amass/amass.(*resolver).monitorPerformance(0xc00006c040)
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:140 +0x1e8
created by github.com/OWASP/Amass/amass.newResolver
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:58 +0x186

goroutine 10 [select]:
github.com/OWASP/Amass/amass.(*resolver).monitorPerformance(0xc00006c100)
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:140 +0x1e8
created by github.com/OWASP/Amass/amass.newResolver
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:58 +0x186

goroutine 11 [select]:
github.com/OWASP/Amass/amass.(*resolver).monitorPerformance(0xc00006c140)
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:140 +0x1e8
created by github.com/OWASP/Amass/amass.newResolver
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:58 +0x186

goroutine 12 [select]:
github.com/OWASP/Amass/amass.(*resolver).monitorPerformance(0xc00006c180)
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:140 +0x1e8
created by github.com/OWASP/Amass/amass.newResolver
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:58 +0x186

goroutine 13 [select]:
github.com/OWASP/Amass/amass.(*resolver).monitorPerformance(0xc00006c1c0)
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:140 +0x1e8
created by github.com/OWASP/Amass/amass.newResolver
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:58 +0x186

goroutine 19 [select]:
github.com/OWASP/Amass/amass.(*resolver).monitorPerformance(0xc00046e040)
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:140 +0x1e8
created by github.com/OWASP/Amass/amass.newResolver
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:58 +0x186

goroutine 50 [select]:
github.com/OWASP/Amass/amass.(*resolver).monitorPerformance(0xc00010c0c0)
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:140 +0x1e8
created by github.com/OWASP/Amass/amass.newResolver
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:58 +0x186

goroutine 51 [runnable]:
github.com/OWASP/Amass/amass/utils.(*SimpleSemaphore).Acquire(0xc00006e000, 0x15e90)
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/utils/semaphores.go:43 +0x40
github.com/OWASP/Amass/amass.(*resolver).monitorPerformance(0xc00010c100)
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:133 +0x618
created by github.com/OWASP/Amass/amass.newResolver
	/go/src/github.com/OWASP/Amass/parts/netdomains/go/src/github.com/OWASP/Amass/amass/resolvers.go:58 +0x186

**Comment by caffix** [comment]
Your IP address range is invalid (has five octets), but thank you for revealing the weakness in our input validation. We will be sure to fix that soon. In the mean time, you should still be able to use the tool with a valid parameter.
