### ISSUE TITLE
panic: page x already freed

### ISSUE THREAD

**Issue by nvqna** [OWASP/Amass#758]
I'm receiving an error when using `enum`. When enumeration completes, after "Discoveries are being migrated into the local database" is printed, the following error occurs:

```
The enumeration has finished
Discoveries are being migrated into the local database
panic: page 2 already freed

goroutine 1 [running]:
github.com/boltdb/bolt.(*freelist).free(0xc002d7ac30, 0x6, 0x7fa6964da000)
	/home/runner/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/freelist.go:121 +0x2aa
github.com/boltdb/bolt.(*node).spill(0xc008a6ca80, 0xc00897d920, 0xc0110a4f78)
	/home/runner/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/node.go:363 +0x405
github.com/boltdb/bolt.(*Bucket).spill(0xc01c1cb440, 0xc0110a5000, 0x3)
	/home/runner/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:570 +0x49a
github.com/boltdb/bolt.(*Bucket).spill(0xc003fc2ef8, 0x4717862c41, 0x22519c0)
	/home/runner/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:537 +0x3f6
github.com/boltdb/bolt.(*Tx).Commit(0xc003fc2ee0, 0xc003373024, 0x632e55b43e4e)
	/home/runner/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/tx.go:163 +0xe8
github.com/hidal-go/hidalgo/kv/bolt.(*Tx).Commit(0xc01b6fc1d0, 0x1aab1c8, 0xc000132008, 0x7fa6969baf10, 0xc0001ce900)
	/home/runner/go/pkg/mod/github.com/hidal-go/hidalgo@v0.0.0-20201109092204-05749a6d73df/kv/bolt/bolt.go:134 +0x2e
github.com/cayleygraph/cayley/graph/kv.(*mTx).Commit(0xc01cf06f00, 0x1aab1c8, 0xc000132008, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/cayleygraph/cayley@v0.7.7-0.20210618132536-7ef662d4c347/graph/kv/metrics.go:126 +0x78
github.com/cayleygraph/cayley/graph/kv.(*QuadStore).ApplyDeltas(0xc006677550, 0xc009088000, 0x32, 0x32, 0xc0178d0101, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/cayleygraph/cayley@v0.7.7-0.20210618132536-7ef662d4c347/graph/kv/indexing.go:669 +0xc38
github.com/caffix/netmap.copyQuads(0x1aab200, 0xc01969af60, 0xc00a4bb6c0, 0xc0027cd000, 0x32, 0x40, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/caffix/netmap@v0.0.0-20211113232947-ff0f98460b11/migrate.go:108 +0x24b
github.com/caffix/netmap.(*Graph).Migrate(0xc00938ae20, 0x1aab200, 0xc01969af60, 0xc00a208400, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/caffix/netmap@v0.0.0-20211113232947-ff0f98460b11/migrate.go:36 +0x345
main.runEnumCommand(0xc00011e770, 0xb, 0xb)
	/home/runner/work/Amass/Amass/cmd/amass/enum.go:278 +0x10f1
main.main()
	/home/runner/work/Amass/Amass/cmd/amass/main.go:125 +0x53b
```

The command I'm using:
`enum -active -ip -src -brute -active -min-for-recursive 2 -dir ~/domain/amass -d domains.com`

This occurs on Ubuntu and MacOS.

```
 % uname -a
Linux hostname 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 % amass -version
v3.15.2
```

```
% uname -a
Darwin hangfire.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
% ~/tools/amass_macos_amd64/amass -version 
v3.13.4
```

If I check the database, is appears to be empty.
```
% ~/tools/amass_macos_amd64/amass db -names                                                    
Failed to move the data into the in-memory graph database: copyQuads: No quads provided
```

I've tried multiple domains and they all cause the error above, on both Ubuntu and MacOS.

**Comment by Forchapeatl** [comment]
can you retry this command with  the prefix "amass"
`amass enum -active -ip -src -brute -active -min-for-recursive 2 -dir ~/domain/amass -d domains.com`
`

**Comment by nvqna** [comment]
> can you retry this command with the prefix "amass" `amass enum -active -ip -src -brute -active -min-for-recursive 2 -dir ~/domain/amass -d domains.com` `

Yep, that's the command I used. I omitted amass in the output above.

**Comment by Forchapeatl** [comment]
> > can you retry this command with the prefix "amass" `amass enum -active -ip -src -brute -active -min-for-recursive 2 -dir ~/domain/amass -d domains.com` `
> 
> Yep, that's the command I used. I omitted amass in the output above.

I tried the same command on both Windows and Linux and it works perfectly. Please update to amass version 3.16.0
