### ISSUE TITLE
panic: reflect: slice index out of range

### ISSUE THREAD

**Issue by softScheck** [OWASP/Amass#765]
While running Amass (any version, so let's assume `v3.16.0`) it crashes after some time with this error.
All related issues about this crash have been closed, but no fix was provided. Maybe someone can look into this again.
Go Version: `go1.17.6 linux/amd64`

Output:
```
xy@archlinux ~/Desktop/Projekte/xy/amass % ./amass enum -src -ipv4 -config config-fast.ini -o xy-fast.txt

...
[DNS]             x.x.net 203.0.113.1
[BufferOver]      y.y.net 203.0.113.2
[SecurityTrails]  z.z.net 203.0.113.3
panic: reflect: slice index out of range [recovered]
        panic: reflect: slice index out of range

goroutine 27531 [running]:
encoding/json.(*encodeState).marshal.func1(0xc00d98be20)
        /usr/local/go/src/encoding/json/encode.go:326 +0x85
panic(0xfbb9c0, 0x1ae31e0)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
reflect.Value.Index(0xfa5ee0, 0xc008295e20, 0x197, 0x1, 0x10e0100, 0xc0053182d0, 0x199)
        /usr/local/go/src/reflect/value.go:962 +0x1f2
encoding/json.arrayEncoder.encode(0xc01a737830, 0xc026eac000, 0xfa5ee0, 0xc008295e20, 0x197, 0xfb0100)
        /usr/local/go/src/encoding/json/encode.go:886 +0x8d
encoding/json.sliceEncoder.encode(0xc009f34120, 0xc026eac000, 0xfa5ee0, 0xc008295e20, 0x197, 0x100)
        /usr/local/go/src/encoding/json/encode.go:860 +0x8f
encoding/json.structEncoder.encode(0xc03223a900, 0x5, 0x8, 0xc01a737860, 0xc026eac000, 0x10e3fc0, 0xc008295e00, 0x199, 0x1000100)
        /usr/local/go/src/encoding/json/encode.go:759 +0x2ab
encoding/json.ptrEncoder.encode(0xc01a737890, 0xc026eac000, 0x1012aa0, 0xc008295e00, 0x16, 0x1010100)
        /usr/local/go/src/encoding/json/encode.go:915 +0x125
encoding/json.(*encodeState).reflectValue(0xc026eac000, 0x1012aa0, 0xc008295e00, 0x16, 0xc00d980100)
        /usr/local/go/src/encoding/json/encode.go:358 +0x82
encoding/json.(*encodeState).marshal(0xc026eac000, 0x1012aa0, 0xc008295e00, 0xc006e20100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:330 +0xf4
encoding/json.(*Encoder).Encode(0xc00d98bf40, 0x1012aa0, 0xc008295e00, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:206 +0x8b
main.saveJSONOutput(0xc0000c06e0, 0xc00050c000, 0xc006e2a780, 0xc006dda6c0)
        /home/caffix/go/src/github.com/OWASP/Amass/cmd/amass/enum.go:489 +0x2f6
created by main.runEnumCommand
        /home/caffix/go/src/github.com/OWASP/Amass/cmd/amass/enum.go:212 +0x8d7
./amass_linux_amd64_3111/amass enum -src -ipv4 -config config-fast.ini -o   214,60s user 7,02s system 163% cpu 2:15,45 total

```

config-fast.ini
```
# Participating data source providers give service credits when enumeration findings are shared.
share = false

# Should results only be collected passively and without DNS resolution? Not recommended.
#mode = passive
# Would you like to use active techniques that communicate directly with the discovered assets, 
# such as pulling TLS certificates from discovered IP addresses and attempting DNS zone transfers?
mode = active

# The directory that stores the Cayley graph database and other output files
# The default for Linux systems is: $HOME/.config/amass
#output_directory = amass

# Another location (directory) where the user can provide ADS scripts to the engine.
#scripts_directory = 

# The maximum number of DNS queries that can be performed concurrently during the enumeration.
#maximum_dns_queries = 20000

# DNS resolvers used globally by the amass package.
[resolvers]
resolver = 1.1.1.1 ; Cloudflare
resolver = 8.8.8.8 ; Google
resolver = 64.6.64.6 ; Verisign
resolver = 74.82.42.42 ; Hurricane Electric
resolver = 1.0.0.1 ; Cloudflare Secondary
resolver = 8.8.4.4 ; Google Secondary
resolver = 64.6.65.6 ; Verisign Secondary
resolver = 77.88.8.8 ; Yandex.DNS Secondary

[scope]
# The network infrastructure settings expand scope, not restrict the scope.
# Single IP address or range (e.g. a.b.c.10-245)
#address = 192.168.1.1
#cidr = 192.168.1.0/24
#asn = 26808
#port = 80
#port = 443
#port = 8080
#port = 8443

cidr = 203.0.113.1/28


# Root domain names used in the enumeration. The findings are limited by the root domain names provided.
[scope.domains]
domain = x.com
domain = y.com
domain = z.com
#domain = owasp.org
#domain = appsecusa.org
#domain = appsec.eu
#domain = appsec-labs.com

# Are there any subdomains that are out of scope?
#[scope.blacklisted]
#subdomain = education.appsec-labs.com
#subdomain = 2012.appsecusa.org

# The graph database discovered DNS names, associated network infrastructure, results from data sources, etc.
# This information is then used in future enumerations and analysis of the discoveries.
#[graphdbs]
#local_database = true ; Set this to false to disable use of the local database.

# postgres://[username:password@]host[:port]/database-name?sslmode=disable of the PostgreSQL 
# database and credentials. Sslmode is optional, and can be disable, require, verify-ca, or verify-full.
#[graphdbs.postgres]
#primary = false ; Specify which graph database is the primary db, or the local database will be selected.
#url = "postgres://[username:password@]host[:port]/database-name?sslmode=disable"
#options="connect_timeout=10"

# MqSQL database and credentials URL format:
# [username:password@]tcp(host[:3306])/database-name?timeout=10s
#[graphdbs.mysql]
#url = [username:password@]tcp(host[:3306])/database-name?timeout=10s

# Settings related to DNS name brute forcing.
[bruteforce]
enabled = false
recursive = false
# Number of discoveries made in a subdomain before performing recursive brute forcing: Default is 1.
#minimum_for_recursive = 1
wordlist_file = /home/xy/Desktop/Projekte/xy/amass/subdomains.txt
#wordlist_file = /usr/share/wordlists/all.txt # multiple lists can be used

# Would you like to permute resolved names?
[alterations]
enabled = false
# edit_distance specifies the number of times a primitive edit operation will be
# performed on a name sample during fuzzy label searching.
#edit_distance = 1 ; Setting this to zero will disable this expensive feature.
flip_words = true   # test-dev.owasp.org -> test-prod.owasp.org
flip_numbers = true # test1.owasp.org -> test2.owasp.org
add_words = true    # test.owasp.org -> test-dev.owasp.org
add_numbers = true  # test.owasp.org -> test1.owasp.org
# Multiple lists can be used.
#wordlist_file = /usr/share/wordlists/all.txt
#wordlist_file = /usr/share/wordlists/all.txt

[data_sources]
# When set, this time-to-live is the minimum value applied to all data source caching.
minimum_ttl = 200 

# Are there any data sources that should be disabled?
#[data_sources.disabled]
#data_source = Ask
#data_source = Bing

# Provide data source configuration information.
# See the following format:
#[data_sources.SOURCENAME] ; The SOURCENAME must match the name in the data source implementation.
#ttl = 4320 ; Time-to-live value sets the number of minutes that the responses are cached.
# Unique identifier for this set of SOURCENAME credentials.
# Multiple sets of credentials can be provided and will be randomly selected.
#[data_sources.SOURCENAME.CredentialSetID]
#apikey = ; Each data source uses potentially different keys for authentication.
#secret = ; See the examples below for each data source.
#username =
#password =

# https://passivedns.cn (Contact)
#[data_sources.360PassiveDNS]
#[data_sources.360PassiveDNS.Credentials]
#apikey =

# https://ahrefs.com (Paid)
#[data_sources.Ahrefs]
#ttl = 4320
#[data_sources.Ahrefs.Credentials]
#apikey =

# https://otx.alienvault.com (Free)
[data_sources.AlienVault]
[data_sources.AlienVault.Credentials]
apikey = xxx

# https://app.binaryedge.com (Paid/Free-trial)
[data_sources.BinaryEdge]
ttl = 10080
[data_sources.BinaryEdge.Credentials]
apikey = xxx

# https://tls.bufferover.run/dns?q=.example.com (Paid/Free)
#[data_sources.BufferOver]
#[data_sources.BufferOver.Credentials]
#apikey =

# https://builtwith.com (Paid/Free-trial)
#[data_sources.BuiltWith]
#ttl = 10080
#[data_sources.BuiltWith.Credentials]
#apikey =

# https://c99.nl (Paid)
#[data_sources.C99]
#ttl = 4320
#[data_sources.C99.account1]
#apikey =
#[data_sources.C99.account2]
#apikey =

# https://censys.io (Paid/Free-trial)
[data_sources.Censys]
ttl = 10080
[data_sources.Censys.Credentials]
apikey = xxx
secret = xxx

# https://chaos.projectdiscovery.io (Invite-Only)
#[data_sources.Chaos]
#ttl = 4320
#[data_sources.Chaos.Credentials]
#apikey =

# https://cloudflare.com (Free)
# Cloudflare apikey is the API token with dns_records and zone read permission
[data_sources.Cloudflare]
[data_sources.Cloudflare.Credentials]
apikey = xxx

# https://circl.lu (Contact)
[data_sources.CIRCL]
[data_sources.CIRCL.Credentials]
username = xxx
password = xxx

# https://dnsdb.info (Paid)
[data_sources.DNSDB]
ttl = 4320
[data_sources.DNSDB.Credentials]
apikey = xxx

# https://dnslytics.com (Paid)
#[data_sources.DNSlytics]
#[data_sources.DNSlytics.Credentials]
#apikey =

# https://dnsrepo.noc.org (Paid)
#[data_sources.DNSRepo]
#[data_sources.DNSRepo.Credentials]
#apikey =

# https://detectify.com (Paid)
#[data_sources.Detectify]
#[data_sources.Detectify.Credentials]
#apikey =

# https://developer.facebook.com (Free)
# Look here for how to obtain the Facebook credentials:
# https://goldplugins.com/documentation/wp-social-pro-documentation/how-to-get-an-app-id-and-secret-key-from-facebook/
#[data_sources.FacebookCT]
#ttl = 4320
#[data_sources.FacebookCT.app1]
#apikey =
#secret =
#[data_sources.FacebookCT.app2]
#apikey =
#secret =

# https://fofa.so (Paid)
#[data_sources.FOFA]
#ttl = 10080
#[data_sources.FOFA.Credentials]
#username =
#apikey =

# https://github.com (Free)
[data_sources.GitHub]
ttl = 4320
[data_sources.GitHub.accountname]
apikey = xxx

# https://gitlab.com (Freemium)
#[data_sources.GitLab]
#[data_sources.GitLab.free]
#apikey =
#[data_sources.GitLab.premium]
#apikey =

# https://hackertarget.com (Paid/Free)
# HackerTarget can be used without an API key, but the key allows better results
#[data_sources.HackerTarget]
#ttl = 1440
#[data_sources.HackerTarget.Credentials]
#apikey =

# https://hunter.io (Paid/Free-trial)
#[data_sources.Hunter]
#[data_sources.Hunter.Credentials]
#apikey =

#[data_sources.IntelX]
#[data_sources.IntelX.Credentials]
#apikey =

# https://ipdata.co (Free)
#[data_sources.IPdata]
#[data_sources.IPdata.Credentials]
#apikey =

# https://ipinfo.io (Paid/Free-trial)
#[data_sources.IPinfo]
#[data_sources.IPinfo.Credentials]
#apikey =

# https://networksdb.io (Paid/Free-trial)
[data_sources.NetworksDB]
[data_sources.NetworksDB.Credentials]
apikey = xxx

# https://onyphe.io (Free)
#[data_sources.ONYPHE]
#ttl = 10080
#[data_sources.ONYPHE.Credentials]
#apikey =

# https://passivetotal.com (Paid/Free-trial)
[data_sources.PassiveTotal]
ttl = 10080
[data_sources.PassiveTotal.Credentials]
username = xxx
apikey = xxx

# https://pentest-tools.com (Paid)
#[data_sources.PentestTools]
#ttl = 10080
#[data_sources.PentestTools.Credentials]
#apikey =

# https://quake.360.cn (Paid)
#[data_sources.Quake]
#ttl = 4320
#[data_sources.Quake.Credentials]
#apikey =

# https://securitytrails.com (Paid/Free-trial)
[data_sources.SecurityTrails]
ttl = 1440
[data_sources.SecurityTrails.Credentials]
apikey = xxx

# https://shodan.io (Paid/Free-trial)
[data_sources.Shodan]
ttl = 10080
[data_sources.Shodan.Credentials]
apikey = xxx

# https://spamhaus.com (Free)
#[data_sources.Spamhaus]
#ttl = 1440
#[data_sources.Spamhaus.Credentials]
#username =
#password =

# https://spyse.com (Paid/Free-trial)
[data_sources.Spyse]
ttl = 4320
[data_sources.Spyse.Credentials]
apikey = xxx

# https://threatbook.cn (Paid)
#[data_sources.ThreatBook]
#[data_sources.ThreatBook.account1]
#apikey=

# https://developer.twitter.com (Free)
# Provide your Twitter App Consumer API key and Consumer API secret key
#[data_sources.Twitter]
#[data_sources.Twitter.account1]
#apikey =
#secret =
#[data_sources.Twitter.account2]
#apikey =
#secret =

# https://umbrella.cisco.com (Paid-Enterprise)
# The apikey must be an API access token created through the Investigate management UI
#[data_sources.Umbrella]
#[data_sources.Umbrella.Credentials]
#apikey =

# https://urlscan.io (Paid/Free-trial)
# URLScan can be used without an API key, but the key allows new submissions to be made
[data_sources.URLScan]
[data_sources.URLScan.Credentials]
apikey = xxx

# https://virustotal.com (Paid/Free-trial)
[data_sources.VirusTotal]
ttl = 10080
[data_sources.VirusTotal.Credentials]
apikey = xxx

# https://whoisxmlapi.com (Paid/Free-trial)
[data_sources.WhoisXMLAPI]
[data_sources.WhoisXMLAPI.Credentials]
apikey = xxx

# https://zetalytics.com (Paid/Invite-Only)
#[data_sources.ZETAlytics]
#ttl = 1440
#[data_sources.ZETAlytics.Credentials]
#apikey =

[data_sources.ZoomEye]
ttl = 1440
[data_sources.ZoomEye.Credentials]
username = xxx
password = xxx
 
```

**Comment by gfrancqu** [comment]
any update for this issue ?
